import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const elements=new Map(),handlers={};const get=s=>{if(!elements.has(s))elements.set(s,{value:'',innerHTML:'',textContent:'',style:{},classList:{toggle(){}},focus(){},addEventListener(){}});return elements.get(s)};
const document={documentElement:{lang:''},querySelector:get,querySelectorAll(){return []},addEventListener(type,fn){handlers[type]=fn},removeEventListener(type){delete handlers[type]}};const storage=new Map(),alerts=[],opened=[];
const requested=[];const fixture={idMeal:'52771',strMeal:'Spicy Arrabiata Penne',strMealThumb:'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',strCategory:'Vegetarian',strArea:'Italian',strInstructions:'Boil pasta; prepare garlic and tomato sauce; combine and serve.',strIngredient1:'penne rigate',strMeasure1:'1 pound',strIngredient2:'olive oil',strMeasure2:'1/4 cup'};
const context={navigator:{},document,window:{open:url=>opened.push(url)},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:async url=>{requested.push(String(url));if(String(url).includes('lookup.php?i=52771'))return {ok:true,json:async()=>({meals:[fixture]})};if(String(url).includes('filter.php?a=Canadian'))return {ok:true,json:async()=>({meals:Array.from({length:101},(_,i)=>({idMeal:'c'+i,strMeal:'Canadian recipe '+i,strMealThumb:'https://www.themealdb.com/images/media/meals/example.jpg'}))})};if(String(url).includes('filter.php?c=Dessert'))return {ok:true,json:async()=>({meals:[{idMeal:'6001',strMeal:'Fruit Tart',strMealThumb:'https://www.themealdb.com/images/media/meals/tart.jpg'}]})};if(String(url).includes('filter.php?a=Non_Alcoholic'))return {ok:true,json:async()=>({drinks:[{idDrink:'11007',strDrink:'Lemon Cooler',strDrinkThumb:'https://www.thecocktaildb.com/images/media/drink/lemon.jpg'}]})};if(String(url).includes('lookup.php?i=11007'))return {ok:true,json:async()=>({drinks:[{idDrink:'11007',strDrink:'Lemon Cooler',strDrinkThumb:'https://www.thecocktaildb.com/images/media/drink/lemon.jpg',strInstructions:'Combine lemon and water.',strIngredient1:'Lemon',strMeasure1:'1'}]})};if(String(url).includes('filter.php?i=shrimp'))return {ok:true,json:async()=>({meals:[{idMeal:'52800',strMeal:'Shrimp Curry',strMealThumb:'https://www.themealdb.com/images/media/meals/example.jpg'}]})};throw Error('mock API unavailable')},setTimeout,clearTimeout,AbortController,Date,Intl,Number,URL,Blob,console,alert:x=>alerts.push(x),confirm:()=>true,prompt:()=>null,location:{hash:''}};
vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/\}\)\(\);\s*$/, 'globalThis.__testRawScale=rawScale;})();'),context);
await new Promise(resolve=>setTimeout(resolve,20));
assert.equal(vm.runInContext("__testRawScale('1 1/2 cups',2)",context),'3 cups');assert.equal(vm.runInContext("__testRawScale('1–2 cups',2)",context),'1–2 cups');assert.equal(vm.runInContext("__testRawScale('to taste',2)",context),'to taste');
assert.match(get('#app').innerHTML,/id="worldGrid"/);assert.match(get('#app').innerHTML,/id="marketSelect"/);assert.match(get('#count').textContent,/Wybrane kategorie/);assert.match(get('#grid').innerHTML,/Fruit Tart/);
function click(action,id){handlers.click({target:{closest(){return {dataset:{do:action,id}}}}})}
for(const [action,title] of [['pantry','Moja spiżarnia'],['journal','Dziennik treningowy'],['venture','Projekt restauracji'],['shopping','Zakupy i budżet'],['restaurant','Studio restauracji'],['partner','Partnerstwa w Stołowniku']]){click(action);assert.ok(get('#dialogRoot').innerHTML.includes(title),action)}
click('open','52771');await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#dialogRoot').innerHTML,/Spicy Arrabiata Penne/);assert.match(get('#dialogRoot').innerHTML,/Źródło nie podaje liczby porcji/);get('#baseServings').value='2';get('#targetServings').value='4';get('#targetServings').onchange();await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#dialogRoot').innerHTML,/Ilości przeliczono z 2 na 4 porcji/);assert.match(get('#dialogRoot').innerHTML,/0,5 cup olive oil/);
handlers.click({target:{closest(){return {dataset:{do:'addPlan',id:'52771',serv:'4',base:'2'}}}}});assert.match(get('#dialogRoot').innerHTML,/Plan tygodnia/);assert.equal(get('#planBase').value,'2');assert.equal(get('#planServings').value,'4');get('#mealChoice').value='52771';get('#day').value='Wtorek';click('planAdd');click('planShop');await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#dialogRoot').innerHTML,/2 pound penne rigate/);assert.match(get('#dialogRoot').innerHTML,/Wtorek · Spicy Arrabiata Penne/);get('#storeProduct').value='rice';get('#storePlace').value='Warszawa';click('storeMap');assert.match(opened.at(-1),/maps\/search\/\?api=1/);click('storeWeb');assert.match(opened.at(-1),/google\.com\/search\?q=/);
get('#search').value='krewetki';get('#searchForm').onsubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));assert.ok(requested.some(x=>x.includes('filter.php?i=shrimp')));assert.match(get('#grid').innerHTML,/Shrimp Curry/);assert.match(get('#count').textContent,/1 /);click('desserts');await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#grid').innerHTML,/Fruit Tart/);click('drinks');await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#grid').innerHTML,/Lemon Cooler/);assert.match(get('#grid').innerHTML,/TheCocktailDB/);click('open','drink-11007');await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#dialogRoot').innerHTML,/Combine lemon and water/);get('#area').value='Canadian';get('#area').onchange();await new Promise(resolve=>setTimeout(resolve,0));assert.match(get('#count').textContent,/101 /);console.log('UI smoke: source lookup, portions, plan-to-shopping and Polish shrimp search, desserts, drinks and >100 country response passed.');
