import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
const dir=fs.mkdtempSync(path.join(process.cwd(),'.atlas-catalog-test-'));
const run=(script,args)=>spawnSync(process.execPath,[new URL(script,import.meta.url).pathname,...args],{cwd:dir,encoding:'utf8'});
const recipe={id:'test-1',name:'Fixture drink',category:'Drink',area:'Test',ingredients:[{name:'water',amount:'1 cup'}],steps:['Mix the ingredients.'],photoUrl:'https://example.org/photo.jpg',photoSourceUrl:'https://example.org/photo',sourceUrl:'https://example.org/recipe',sourceName:'Fixture source',recipeLicense:'CC BY 4.0',recipeLicenseUrl:'https://creativecommons.org/licenses/by/4.0/',photoLicense:'CC BY 4.0',photoLicenseUrl:'https://creativecommons.org/licenses/by/4.0/',photoAuthor:'Fixture photographer',rightsProofUrl:'https://example.org/rights',servings:2,nutrition:{kcal:12,proteinG:1,fatG:0,carbsG:2,sourceUrl:'https://example.org/nutrition'},allergens:{items:['milk'],sourceUrl:'https://example.org/allergens'},costEstimate:{amount:4.5,currency:'PLN',market:'PL',checkedAt:'2026-09-17',servings:2,sourceUrl:'https://example.org/price'}};
try{
 fs.writeFileSync(path.join(dir,'input.jsonl'),JSON.stringify(recipe)+'\n');let result=run('import-catalog.mjs',['input.jsonl','catalog.json']);assert.equal(result.status,0,result.stderr);
 result=run('build-shards.mjs',['catalog.json','catalog','100']);assert.equal(result.status,0,result.stderr);
 const rows=JSON.parse(fs.readFileSync(path.join(dir,'catalog/recipes-00000.json'))),index=JSON.parse(fs.readFileSync(path.join(dir,'catalog/catalog-index.json')));
 assert.equal(rows[0].nutrition.kcal,12);assert.equal(rows[0].allergens.items[0],'milk');assert.equal(index[0].photoAuthor,'Fixture photographer');result=run('audit-catalog.mjs',['catalog.json']);assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).withNutrition,1);
 fs.writeFileSync(path.join(dir,'input.jsonl'),JSON.stringify({...recipe,nutrition:{kcal:12,proteinG:1,fatG:0,carbsG:2}})+'\n');result=run('import-catalog.mjs',['input.jsonl','rejected.json']);assert.equal(result.status,1);assert.equal(fs.existsSync(path.join(dir,'rejected.json')),false);
 console.log('Catalog validation: provenance, metadata and shards passed.');
}finally{fs.rmSync(dir,{recursive:true,force:true})}
