// Stołownik — profesjonalny doradca żywieniowy / planer v3
(function(){
const COST={1:12,2:15,3:22,4:31,5:30,6:19,7:29,8:18,9:29,10:23,11:28,12:14,13:31,14:43,15:29,16:19,17:27,18:16,19:22,20:42,21:12,22:17,23:13,24:28,25:38};
const MEAL={breakfast:[1,8,21,22,23],lunch:[2,3,4,5,6,7,9,11,12,13,14,15,17,18,19,20],snack:[8,10,21,22,23,24,25],dinner:[1,6,10,16,20]};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function init(){if(typeof R==='undefined'||typeof N==='undefined')return setTimeout(init,80);if(document.getElementById('advisorPro'))return;
const css=document.createElement('style');css.textContent=`.ap-launch{position:fixed;right:18px;bottom:18px;z-index:40;border:0;border-radius:999px;background:#9b382b;color:#fff;padding:14px 18px;font-weight:900;box-shadow:0 12px 30px #0004}.ap{background:linear-gradient(135deg,#294736,#3d644b);color:#fff;border-radius:28px;padding:26px;margin:24px 0;box-shadow:0 18px 45px #21382922}.ap-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.ap h2{font-size:32px;margin:0 0 7px}.ap-sub{margin:0;color:#e8eee9;max-width:760px}.ap-badge{background:#fff2;border:1px solid #fff3;border-radius:999px;padding:8px 12px;font-size:12px;font-weight:900;white-space:nowrap}.ap-steps{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.ap-step{background:#fff2;border:1px solid #fff2;border-radius:999px;padding:7px 10px;font-size:12px}.ap-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ap-card{background:#fff;color:#28231e;border-radius:15px;padding:10px 12px}.ap-card span{display:block;font-size:11px;font-weight:900;color:#756c63;margin-bottom:4px}.ap-card input,.ap-card select{width:100%;border:0;background:transparent;outline:0;font-weight:800;padding:5px 0}.ap-wide{grid-column:span 2}.ap-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px}.ap-btn{border:0;border-radius:13px;padding:12px 16px;font-weight:900;background:#fff;color:#365d45}.ap-btn.primary{background:#9b382b;color:#fff}.ap-result{display:none;margin-top:18px;background:#fff;color:#28231e;border-radius:20px;padding:18px}.ap-result.show{display:block}.ap-targets{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0}.ap-stat{background:#fff8ec;border:1px solid #eadbc9;border-radius:13px;padding:10px;text-align:center}.ap-stat b{display:block;font-size:18px}.ap-stat small{color:#756c63}.ap-day{border-top:1px solid #e6dacb;padding:14px 0}.ap-day:first-of-type{border-top:0}.ap-meal{display:grid;grid-template-columns:100px 1fr auto;gap:10px;align-items:center;padding:5px 0}.ap-note{background:#fff8ec;border-radius:12px;padding:10px;margin-top:12px;font-size:12px}.ap-good{color:#365d45;font-weight:900}.ap-warn{color:#9b382b;font-weight:900}.ap-summary{font-size:14px;line-height:1.5}.ap-divider{height:1px;background:#e9dfd3;margin:13px 0}.ap-muted{color:#756c63;font-size:12px}@media(max-width:900px){.ap-grid{grid-template-columns:1fr 1fr}.ap-wide{grid-column:span 2}.ap-targets{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.ap{padding:18px}.ap-head{display:block}.ap-badge{display:inline-block;margin-top:10px}.ap-grid{grid-template-columns:1fr}.ap-wide{grid-column:span 1}.ap-targets{grid-template-columns:1fr 1fr}.ap-meal{grid-template-columns:1fr}.ap-launch{right:12px;bottom:12px}}`;document.head.appendChild(css);
const launch=document.createElement('button');launch.className='ap-launch';launch.textContent='🍽️ Doradca';document.body.appendChild(launch);
const el=document.createElement('section');el.id='advisorPro';el.className='ap';el.innerHTML=`<div class="ap-head"><div><h2>🍽️ Doradca Stołownika</h2><p class="ap-sub">Nie musisz znać swojego zapotrzebowania. Podaj podstawowe dane, cel i ograniczenia — doradca oszacuje kalorie, makro, budżet i ułoży plan na kilka dni.</p></div><div class="ap-badge">TRYB PRO</div></div><div class="ap-steps"><span class="ap-step">1. Profil</span><span class="ap-step">2. Cel</span><span class="ap-step">3. Preferencje</span><span class="ap-step">4. Automatyczny plan</span></div><div class="ap-grid">
<label class="ap-card"><span>Wiek</span><input id="apAge" type="number" min="18" max="100" placeholder="np. 28"></label><label class="ap-card"><span>Płeć do obliczeń</span><select id="apSex"><option value="m">Mężczyzna</option><option value="f">Kobieta</option></select></label><label class="ap-card"><span>Wzrost (cm)</span><input id="apHeight" type="number" min="130" max="230" placeholder="np. 178"></label><label class="ap-card"><span>Waga (kg)</span><input id="apWeight" type="number" min="35" max="250" step="0.1" placeholder="np. 82"></label>
<label class="ap-card"><span>Aktywność</span><select id="apActivity"><option value="1.2">Mała — głównie siedząco</option><option value="1.375">Lekka — 1–3 treningi/tydz.</option><option value="1.55" selected>Średnia — 3–5 treningów/tydz.</option><option value="1.725">Duża — 6–7 treningów/tydz.</option><option value="1.9">Bardzo duża / praca fizyczna</option></select></label><label class="ap-card"><span>Cel</span><select id="apGoal"><option value="maintain">Utrzymanie wagi</option><option value="lose">Redukcja / chudnięcie</option><option value="gain">Masa / tycie</option><option value="protein">Więcej białka</option><option value="cheap">Jak najtaniej</option></select></label><label class="ap-card"><span>Tempo celu</span><select id="apPace"><option value="gentle">Łagodne</option><option value="normal" selected>Umiarkowane</option><option value="fast">Szybsze</option></select></label><label class="ap-card"><span>Posiłków dziennie</span><select id="apMeals"><option>2</option><option selected>3</option><option>4</option><option>5</option></select></label>
<label class="ap-card"><span>Budżet dzienny (zł)</span><input id="apBudget" type="number" min="1" placeholder="np. 45"></label><label class="ap-card"><span>Maks. czas jednego dania</span><input id="apTime" type="number" min="5" placeholder="np. 40"></label><label class="ap-card"><span>Dieta</span><select id="apDiet"><option value="all">Bez ograniczeń</option><option value="veg">Wegetariańska</option><option value="meat">Głównie mięsna</option><option value="fish">Ryby</option></select></label><label class="ap-card"><span>Poziom gotowania</span><select id="apSkill"><option value="easy">Początkujący</option><option value="normal" selected>Normalny</option><option value="any">Bez znaczenia</option></select></label>
<label class="ap-card"><span>Dni planu</span><select id="apDays"><option value="1">1 dzień</option><option value="3">3 dni</option><option value="5">5 dni</option><option value="7" selected>7 dni</option></select></label><label class="ap-card"><span>Własne kcal (opcjonalnie)</span><input id="apKcal" type="number" min="1000" placeholder="zostaw puste = auto"></label><label class="ap-card"><span>Własne białko g (opcjonalnie)</span><input id="apProtein" type="number" min="0" placeholder="zostaw puste = auto"></label><label class="ap-card"><span>Powtarzanie dań</span><select id="apRepeat"><option value="low">Mało powtórek</option><option value="normal" selected>Normalnie</option><option value="ok">Powtórki są OK</option></select></label>
<label class="ap-card ap-wide"><span>Nie lubię / nie chcę</span><input id="apExclude" placeholder="np. cebula, ryby, twaróg"></label><label class="ap-card ap-wide"><span>Co lubię / preferuję</span><input id="apPrefer" placeholder="np. kurczak, makarony, polskie dania"></label></div><div class="ap-actions"><button class="ap-btn" id="apCalc">Oblicz moje zapotrzebowanie</button><button class="ap-btn primary" id="apPlan">Ułóż mi plan</button></div><div id="apResult" class="ap-result"></div>`;
const anchor=document.querySelector('.daybox');(anchor||document.querySelector('main')||document.body).insertAdjacentElement(anchor?'afterend':'afterbegin',el);launch.onclick=()=>el.scrollIntoView({behavior:'smooth',block:'start'});
const get=id=>document.getElementById(id),num=(id,d=0)=>{let x=parseFloat(get(id).value);return Number.isFinite(x)?x:d};
function profile(){let age=num('apAge'),h=num('apHeight'),w=num('apWeight'),sex=get('apSex').value,act=parseFloat(get('apActivity').value),goal=get('apGoal').value,pace=get('apPace').value;if(!age||!h||!w)return null;let bmr=10*w+6.25*h-5*age+(sex==='m'?5:-161),tdee=bmr*act,delta=pace==='gentle'?200:pace==='fast'?500:350,target=tdee;if(goal==='lose')target-=delta;if(goal==='gain')target+=delta;target=Math.round(clamp(target,sex==='m'?1500:1200,4200));let own=num('apKcal');if(own)target=Math.round(own);let protein=Math.round((goal==='gain'||goal==='protein'?1.8:goal==='lose'?1.6:1.4)*w),ownP=num('apProtein');if(ownP)protein=Math.round(ownP);let fat=Math.round(Math.max(45,target*.27/9)),carbs=Math.round(Math.max(80,(target-protein*4-fat*9)/4));return{age,h,w,sex,bmr:Math.round(bmr),tdee:Math.round(tdee),target,protein,fat,carbs,goal}}
function txt(r){return (r.name+' '+(r.desc||'')+' '+r.ingredients.join(' ')+' '+r.cats.join(' ')).toLowerCase()}
function allowed(r){let diet=get('apDiet').value,ex=get('apExclude').value.toLowerCase().split(',').map(s=>s.trim()).filter(Boolean),maxT=num('apTime',999),skill=get('apSkill').value;if(diet==='veg'&&!r.cats.includes('Wegetariańskie'))return false;if(diet==='meat'&&!r.cats.includes('Mięsne'))return false;if(diet==='fish'&&!r.cats.includes('Ryby'))return false;if(r.time>maxT)return false;if(skill==='easy'&&r.time>60)return false;let t=txt(r);return !ex.some(x=>t.includes(x))}
function score(r,tk,tp,used){let n=N[r.id]||[0,0,0,0,0],goal=get('apGoal').value,pref=get('apPrefer').value.toLowerCase().split(',').map(s=>s.trim()).filter(Boolean),budget=num('apBudget',9999),meals=num('apMeals',3),cost=(COST[r.id]||0)/2,s=120-Math.abs(n[0]-tk)/10-Math.abs(n[1]-tp)*1.15-Math.max(0,cost-budget/meals)*8;if(goal==='lose')s-=n[0]/55;if(goal==='gain')s+=n[0]/60+n[1]/5;if(goal==='protein')s+=n[1]*1.4;if(goal==='cheap')s-=cost*3;if(pref.some(x=>txt(r).includes(x)))s+=12;let rep=get('apRepeat').value;if(used[r.id])s-=used[r.id]*(rep==='low'?35:rep==='normal'?18:5);return s}
function mealPool(type){let ids=MEAL[type]||[];let a=R.filter(r=>ids.includes(r.id)&&allowed(r));return a.length?a:R.filter(allowed)}
function choose(type,tk,tp,used){let a=mealPool(type).slice().sort((x,y)=>score(y,tk,tp,used)-score(x,tk,tp,used));return a[0]||null}
function targetsHTML(p){return `<div class="ap-summary"><b>Twoje automatyczne ustawienia</b><br>Szacunkowe utrzymanie: ok. <b>${p.tdee} kcal</b>. Dla wybranego celu doradca przyjął <b>${p.target} kcal/dzień</b>.</div><div class="ap-targets"><div class="ap-stat"><b>${p.target}</b><small>kcal / dzień</small></div><div class="ap-stat"><b>${p.protein} g</b><small>białko</small></div><div class="ap-stat"><b>${p.fat} g</b><small>tłuszcz</small></div><div class="ap-stat"><b>${p.carbs} g</b><small>węgle</small></div><div class="ap-stat"><b>${p.bmr}</b><small>BMR, szacunek</small></div></div>`}
function calc(){let out=get('apResult'),p=profile();if(!p){out.innerHTML='<b>Uzupełnij wiek, wzrost i wagę — resztę doradca policzy automatycznie.</b>';out.classList.add('show');return}out.innerHTML=targetsHTML(p)+`<div class="ap-note">To są wartości orientacyjne do planowania jedzenia, a nie diagnoza ani indywidualna terapia. Przy chorobach, ciąży, zaburzeniach odżywiania albo szczególnych potrzebach skonsultuj plan ze specjalistą.</div>`;out.classList.add('show')}
function plan(){let out=get('apResult'),p=profile();if(!p){out.innerHTML='<b>Najpierw wpisz wiek, wzrost i wagę — dzięki temu plan nie będzie przypadkowy.</b>';out.classList.add('show');return}let days=num('apDays',7),meals=num('apMeals',3),budget=num('apBudget',9999),used={},types=meals===2?['lunch','dinner']:meals===3?['breakfast','lunch','dinner']:meals===4?['breakfast','lunch','snack','dinner']:['breakfast','snack','lunch','snack','dinner'];let html=targetsHTML(p),weekCost=0;for(let d=1;d<=days;d++){let chosen=[],k=0,pr=0,fa=0,ca=0,cost=0;for(let i=0;i<types.length;i++){let remain=types.length-i,tk=Math.max(250,(p.target-k)/remain),tp=Math.max(10,(p.protein-pr)/remain),r=choose(types[i],tk,tp,used);if(!r)continue;used[r.id]=(used[r.id]||0)+1;chosen.push({r,type:types[i]});let n=N[r.id]||[0,0,0,0,0];k+=n[0];pr+=n[1];fa+=n[2];ca+=n[3];cost+=(COST[r.id]||0)/2}weekCost+=cost;let diff=Math.round(k-p.target),quality=Math.abs(diff)<=250?'Dobrze dopasowane':Math.abs(diff)<=450?'W miarę blisko celu':'Wymaga korekty';html+=`<div class="ap-day"><b>Dzień ${d}</b> · ${Math.round(k)} kcal · ${Math.round(pr)} g białka · ok. ${cost.toFixed(2).replace('.',',')} zł <span class="${Math.abs(diff)<=250?'ap-good':'ap-warn'}">${quality}</span>${chosen.map((x,i)=>`<div class="ap-meal"><small>${['Śniadanie','Obiad','Przekąska','Kolacja'][Math.min(i,3)]||'Posiłek'}</small><span><b>${x.r.name}</b><br><span class="ap-muted">${x.r.time} min · ${(N[x.r.id]||[0])[0]} kcal</span></span><button onclick="openR(${x.r.id})">Przepis</button></div>`).join('')}</div>`}html+=`<div class="ap-divider"></div><div class="ap-summary"><b>Podsumowanie planu:</b> ok. ${weekCost.toFixed(2).replace('.',',')} zł za ${days} dni${budget<9999?` · budżet ${Math.round(budget*days)} zł`:''}. Plan priorytetyzuje Twój cel, makro, czas, dietę, budżet i preferencje.</div><div class="ap-note">Wartości odżywcze i ceny w Stołowniku są szacunkowe. Doradca pomaga zaplanować jedzenie, ale nie zastępuje dietetyka ani lekarza.</div>`;out.innerHTML=html;out.classList.add('show');out.scrollIntoView({behavior:'smooth',block:'nearest'})}
get('apCalc').onclick=calc;get('apPlan').onclick=plan;
}
init();
})();