// Stołownik — Danie dnia v3. Jedno deterministycznie losowane danie na dobę, zmiana o 09:00 Europe/Warsaw.
(function(){
function parts(){const a=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),o={};a.forEach(p=>o[p.type]=p.value);return o}
function key(){const p=parts(),d=new Date(Date.UTC(+p.year,+p.month-1,+p.day));if(+p.hour<9)d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dish(){if(typeof R==='undefined')return null;const a=R.filter(r=>r&&r.id&&r.name&&r.img&&!/koktajl|napój|lemoniada|kawa|herbata/i.test(r.name));return a.length?a[hash('danie-dnia-'+key())%a.length]:null}
function render(){if(typeof R==='undefined'||!document.querySelector('#hubHome'))return setTimeout(render,100);const d=dish();if(!d)return;let card=document.querySelector('#hubHome .featuredDish');if(!card){const hero=document.querySelector('#hubHome .restaurantHero');if(!hero)return;card=document.createElement('div');card.className='featuredDish';hero.appendChild(card)}card.innerHTML=`<div class="featuredLabel">DANIE DNIA · LOSOWANE O 09:00</div><img src="${d.img}" alt="${d.name}"><div class="featuredShade"></div><div class="featuredInfo"><span>DZISIEJSZY WYBÓR STOŁOWNIKA</span><h2>${d.name}</h2><p>${d.time||'—'} min · następne losowanie jutro o 09:00</p><button type="button" id="dailyOpen">Zobacz przepis →</button></div>`;card.querySelector('#dailyOpen').onclick=()=>{if(typeof openR==='function')openR(d.id);else window.stolownikPage&&window.stolownikPage('food')};card.dataset.dailyKey=key()}
function schedule(){const p=parts(),now=+p.hour*60 + +p.minute;let wait=540-now;if(wait<=0)wait+=1440;setTimeout(()=>{render();schedule()},wait*60000+2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{render();schedule()});else{render();schedule()}
})();