// Stołownik — napoje v9: pełne przepisy
(function(){
const pics={'Lemoniada cytrynowa':'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=80','Lemoniada truskawkowa':'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=900&q=80','Woda z cytryną i miętą':'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=900&q=80','Mrożona herbata brzoskwiniowa':'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80','Herbata imbirowo-cytrynowa':'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=80','Kakao domowe':'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=900&q=80','Kawa mrożona':'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80','Latte':'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80','Bananowy koktajl':'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80','Koktajl truskawkowy':'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80','Mango lassi':'https://images.unsplash.com/photo-1570696516188-ade861b84a49?auto=format&fit=crop&w=900&q=80','Smoothie zielone':'https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=900&q=80','Kompot jabłkowy':'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80','Kompot z owoców leśnych':'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80','Napój pomarańczowo-imbirowy':'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80','Virgin mojito':'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=900&q=80','Bezalkoholowa piña colada':'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80','Orzeźwiający ogórek-limonka':'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=900&q=80','Domowy izotonik cytrusowy':'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80','Ciepłe mleko z cynamonem':'https://images.unsplash.com/photo-1576186726115-4d51596775d1?auto=format&fit=crop&w=900&q=80'};
const D=[
['Lemoniada cytrynowa','Zimne','5 min',['2 cytryny','700 ml zimnej wody','2–3 łyżki miodu lub cukru','garść lodu'],['Wyciśnij sok z cytryn.','Wymieszaj sok z wodą i miodem lub cukrem.','Dodaj lód i plasterki cytryny. Podawaj od razu.']],
['Lemoniada truskawkowa','Owocowe','7 min',['250 g truskawek','1 cytryna','700 ml wody','1–2 łyżki miodu','lód'],['Zblenduj truskawki z sokiem z cytryny i miodem.','Połącz z zimną wodą.','Dodaj lód i kilka kawałków truskawek.']],
['Woda z cytryną i miętą','Bez cukru','3 min',['1 l zimnej wody','1 cytryna','garść świeżej mięty','lód'],['Cytrynę dokładnie umyj i pokrój w plasterki.','Lekko rozgnieć miętę w dłoniach.','Połącz wszystko z wodą i lodem.']],
['Mrożona herbata brzoskwiniowa','Herbaty','10 min',['2 torebki czarnej herbaty','500 ml gorącej wody','1 dojrzała brzoskwinia','1 łyżka miodu','lód'],['Zaparz herbatę przez 4–5 minut i wyjmij torebki.','Dodaj miód i wystudź.','Dodaj pokrojoną brzoskwinię oraz dużo lodu.']],
['Herbata imbirowo-cytrynowa','Gorące','8 min',['400 ml gorącej wody','3 cm świeżego imbiru','1/2 cytryny','1–2 łyżeczki miodu'],['Imbir pokrój w cienkie plasterki i zalej gorącą wodą.','Parz około 5 minut.','Dodaj cytrynę, a po lekkim przestudzeniu miód.']],
['Kakao domowe','Gorące','7 min',['400 ml mleka','2 łyżki kakao','1–2 łyżki cukru','szczypta cynamonu'],['Podgrzej większość mleka.','Resztę mleka wymieszaj dokładnie z kakao i cukrem.','Wlej mieszankę do garnka i podgrzewaj, mieszając, aż kakao będzie gładkie.']],
['Kawa mrożona','Kawy','6 min',['2 porcje espresso lub 120 ml mocnej kawy','200 ml zimnego mleka','garść lodu','1 łyżeczka syropu lub cukru — opcjonalnie'],['Przygotuj kawę i krótko ją przestudź.','Napełnij wysoką szklankę lodem.','Wlej mleko i kawę, dodaj słodzik według smaku i wymieszaj.']],
['Latte','Kawy','6 min',['1 porcja espresso','200 ml mleka'],['Przygotuj espresso w dużej filiżance.','Podgrzej i spień mleko.','Powoli wlej mleko do kawy, na końcu dodając piankę.']],
['Bananowy koktajl','Koktajle','4 min',['1 dojrzały banan','250 ml mleka lub napoju roślinnego','2 łyżki płatków owsianych','szczypta cynamonu'],['Obierz banana.','Umieść wszystkie składniki w blenderze.','Blenduj około 30–45 sekund do gładkości.']],
['Koktajl truskawkowy','Koktajle','4 min',['250 g truskawek','200 ml kefiru lub jogurtu pitnego','1 łyżeczka miodu'],['Umyj i oczyść truskawki.','Dodaj kefir i miód.','Zblenduj na gładki koktajl.']],
['Mango lassi','Koktajle','5 min',['1 dojrzałe mango','200 g jogurtu naturalnego','100 ml zimnej wody lub mleka','szczypta kardamonu'],['Obierz mango i oddziel miąższ od pestki.','Zblenduj mango z jogurtem i wodą lub mlekiem.','Dodaj kardamon i podawaj dobrze schłodzone.']],
['Smoothie zielone','Koktajle','5 min',['1 banan','1 garść szpinaku','1 kiwi','200 ml soku jabłkowego lub wody','1 łyżeczka soku z cytryny'],['Umyj szpinak i obierz owoce.','Włóż wszystko do blendera.','Blenduj do uzyskania jednolitej konsystencji.']],
['Kompot jabłkowy','Domowe','30 min',['4 jabłka','1,2 l wody','1 kawałek cynamonu','2 goździki','cukier lub miód do smaku'],['Jabłka umyj, usuń gniazda nasienne i pokrój na kawałki.','Zalej wodą, dodaj cynamon i goździki.','Gotuj łagodnie około 20–25 minut. Dosłodź do smaku.']],
['Kompot z owoców leśnych','Domowe','25 min',['400 g owoców leśnych świeżych lub mrożonych','1,2 l wody','2–3 łyżki cukru lub miodu'],['Owoce przełóż do garnka i zalej wodą.','Doprowadź do wrzenia i gotuj na małym ogniu około 15 minut.','Dosłodź według smaku i podawaj ciepły albo schłodzony.']],
['Napój pomarańczowo-imbirowy','Owocowe','5 min',['2 pomarańcze','1 cm świeżego imbiru','250 ml zimnej wody','1 łyżeczka miodu — opcjonalnie'],['Wyciśnij sok z pomarańczy.','Imbir drobno zetrzyj.','Połącz sok, imbir i wodę. W razie potrzeby dodaj miód.']],
['Virgin mojito','Bezalkoholowe','5 min',['1 limonka','8–10 listków mięty','2 łyżeczki cukru trzcinowego','200 ml wody gazowanej','kruszony lód'],['Pokrój limonkę i delikatnie ugnieć ją w szklance z cukrem.','Dodaj miętę i lekko ją dociśnij, nie rozrywając mocno liści.','Wsyp lód, dolej wodę gazowaną i wymieszaj.']],
['Bezalkoholowa piña colada','Bezalkoholowe','5 min',['200 ml soku ananasowego','100 ml mleczka kokosowego','100 g ananasa','garść lodu'],['Umieść sok, mleczko kokosowe, ananasa i lód w blenderze.','Blenduj do kremowej konsystencji.','Przelej do schłodzonej szklanki i podawaj od razu.']],
['Orzeźwiający ogórek-limonka','Bez cukru','5 min',['1/2 ogórka','1 limonka','600 ml zimnej wody','kilka listków mięty','lód'],['Ogórek i limonkę pokrój w cienkie plasterki.','Dodaj miętę oraz lód.','Zalej zimną wodą i odstaw na kilka minut, aby smaki się połączyły.']],
['Domowy izotonik cytrusowy','Sport','5 min',['500 ml wody','sok z 1/2 cytryny','sok z 1/2 pomarańczy','1 łyżka miodu','mała szczypta soli'],['Wlej wodę i soki do butelki lub dzbanka.','Dodaj miód oraz małą szczyptę soli.','Mieszaj lub potrząsaj do rozpuszczenia. Podawaj schłodzony.']],
['Ciepłe mleko z cynamonem','Gorące','5 min',['300 ml mleka','1/2 łyżeczki cynamonu','1 łyżeczka miodu'],['Podgrzej mleko, nie doprowadzając go do mocnego wrzenia.','Dodaj cynamon i dokładnie wymieszaj.','Po lekkim przestudzeniu dodaj miód.']]
];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function boot(){const main=document.querySelector('main');if(!main)return setTimeout(boot,100);document.querySelectorAll('.catalogChooser').forEach(x=>x.remove());if(document.getElementById('drinkCatalog'))return;
let st=document.createElement('style');st.textContent='.drinkCat{display:none;max-width:1280px;margin:18px auto 70px;padding:46px 38px 60px;background:#fffaf1;border:1px solid #d7b995;border-radius:22px;box-shadow:0 30px 85px #51331f18;font-family:Manrope,system-ui,sans-serif}.drinkCat.show{display:block}.drinkPills{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0 30px}.drinkGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.drinkCard{background:#fff;border:1px solid #dcc7ad;border-radius:15px;overflow:hidden}.drinkCard img{width:100%;height:250px;object-fit:cover;display:block}.drinkBody{padding:20px}.drinkOpen{width:100%;margin-top:16px;border:1px solid #70301f;background:linear-gradient(#93472f,#783522);color:#fff8ef;border-radius:9px;padding:13px 16px;font-weight:800;font-size:15px}.drinkRecipe{position:fixed;inset:0;z-index:10020;background:#1b110de8;display:none;align-items:center;justify-content:center;padding:24px}.drinkRecipe.show{display:flex}.drinkSheet{position:relative;width:min(760px,100%);max-height:90vh;overflow:auto;background:#fff9ef;border-radius:18px;box-shadow:0 35px 100px #0007}.drinkSheet img{width:100%;height:310px;object-fit:cover}.drinkInside{padding:30px}.drinkInside h2,.drinkInside h3{font-family:"Cormorant Garamond",Georgia,serif;font-style:italic}.drinkInside h2{font-size:48px;line-height:.95;margin:4px 0 10px}.drinkInside h3{font-size:30px;margin:26px 0 10px}.drinkInside li{margin:8px 0;line-height:1.55}.drinkClose{position:absolute;right:14px;top:14px;width:46px;height:46px;border-radius:50%;border:1px solid #d1b18e;background:#fff9ef;color:#33231c;font-size:27px;font-weight:800;z-index:2}.drinkMeta{font-weight:800;color:#875038}.drinkSteps{counter-reset:drinkstep;list-style:none;padding:0}.drinkSteps li{counter-increment:drinkstep;display:grid;grid-template-columns:36px 1fr;gap:10px;align-items:start}.drinkSteps li:before{content:counter(drinkstep);display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#314b39;color:white;font-weight:800}.drinkCat #drinkQ{width:100%;margin-top:22px;padding:17px 19px;border:1px solid #cfae8b;border-radius:12px;background:#fffdf8;font-size:17px}@media(max-width:800px){.drinkGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.drinkGrid{grid-template-columns:1fr}.drinkCat{margin:12px;padding:30px 18px 42px}.drinkRecipe{padding:0;align-items:stretch}.drinkSheet{height:100dvh;max-height:100dvh;border-radius:0;width:100%;-webkit-overflow-scrolling:touch}.drinkSheet img{height:225px}.drinkInside{padding:23px 18px 40px}.drinkInside h2{font-size:40px}.drinkClose{position:fixed;top:12px;right:12px}}';document.head.appendChild(st);
let sec=document.createElement('section');sec.id='drinkCatalog';sec.className='drinkCat';sec.innerHTML='<div class="section-head"><span class="eyebrow">KATALOG NAPOJÓW</span><h2>Napoje</h2><p>Domowe napoje na zimno i na ciepło. Każdy ma teraz dokładny przepis ze składnikami i przygotowaniem.</p></div><input id="drinkQ" placeholder="Szukaj napoju…"><div id="drinkPills" class="drinkPills"></div><div id="drinkGrid" class="drinkGrid"></div>';main.parentNode.insertBefore(sec,main.nextSibling);
let modal=document.createElement('div');modal.id='drinkRecipe';modal.className='drinkRecipe';document.body.appendChild(modal);
let cat='Wszystkie',cats=['Wszystkie',...new Set(D.map(x=>x[1]))];function render(){let q=document.getElementById('drinkQ').value.toLowerCase(),a=D.filter(x=>(cat==='Wszystkie'||x[1]===cat)&&(!q||x[0].toLowerCase().includes(q)||x[3].join(' ').toLowerCase().includes(q)));drinkPills.innerHTML=cats.map(c=>'<button class="drinkPill '+(c===cat?'on':'')+'" data-c="'+esc(c)+'">'+esc(c)+'</button>').join('');drinkGrid.innerHTML=a.map(x=>'<article class="drinkCard"><img src="'+pics[x[0]]+'" alt="'+esc(x[0])+'" loading="lazy"><div class="drinkBody"><small>'+esc(x[1])+' · '+esc(x[2])+'</small><h3>'+esc(x[0])+'</h3><button class="drinkOpen" data-drink="'+esc(x[0])+'">Zobacz przepis</button></div></article>').join('')}
function openDrink(name){let x=D.find(d=>d[0]===name);if(!x)return;modal.innerHTML='<div class="drinkSheet"><button class="drinkClose" aria-label="Zamknij">×</button><img src="'+pics[x[0]]+'" alt="'+esc(x[0])+'"><div class="drinkInside"><div class="drinkMeta">'+esc(x[1])+' · '+esc(x[2])+'</div><h2>'+esc(x[0])+'</h2><p>Proporcje na około 2 porcje.</p><h3>Składniki</h3><ul>'+x[3].map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul><h3>Przygotowanie</h3><ol class="drinkSteps">'+x[4].map(i=>'<li>'+esc(i)+'</li>').join('')+'</ol></div></div>';modal.classList.add('show');document.body.style.overflow='hidden';modal.querySelector('.drinkSheet').scrollTop=0}
function closeDrink(){modal.classList.remove('show');document.body.style.overflow=''}
drinkPills.onclick=e=>{let b=e.target.closest('[data-c]');if(b){cat=b.dataset.c;render()}};drinkQ.oninput=render;drinkGrid.onclick=e=>{let b=e.target.closest('[data-drink]');if(b)openDrink(b.dataset.drink)};modal.onclick=e=>{if(e.target===modal||e.target.closest('.drinkClose'))closeDrink()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))closeDrink()});
const compat=document.createElement('button');compat.id='drinkTab';compat.hidden=true;compat.onclick=()=>{main.style.display='block';sec.classList.add('show');render()};document.body.appendChild(compat);window.showDrinkCatalog=()=>compat.click();window.hideDrinkCatalog=()=>{sec.classList.remove('show');closeDrink()};document.getElementById('foodMore10')?.remove();document.querySelectorAll('.foodMore,.drinkMore,.catalogChooser').forEach(x=>x.remove());render()}
boot();})();