// Stołownik — informacje prawne i zasady licencji v1
(function(){
function boot(){
 const main=document.querySelector('main'); if(!main)return setTimeout(boot,120);
 if(document.getElementById('legalPanel'))return;
 const box=document.createElement('section'); box.id='legalPanel'; box.hidden=true;
 box.innerHTML=`<div class="legalIn"><button id="legalClose" type="button" aria-label="Zamknij">×</button><span class="eyebrow">INFORMACJE PRAWNE</span><h2>Źródła, licencje i prywatność</h2><p><b>Zdjęcia.</b> Stołownik korzysta ze zdjęć z Wikimedia Commons oraz Unsplash. Pliki Wikimedia mogą mieć różne wolne licencje; autor, źródło i warunki konkretnego pliku znajdują się na jego stronie opisu. Materiały z Unsplash są używane zgodnie z licencją Unsplash. Stołownik nie przypisuje sobie autorstwa cudzych fotografii.</p><p><b>Wikimedia Commons.</b> Przy materiałach wymagających uznania autorstwa należy zachować autora, źródło i oznaczenie licencji. Jeżeli zdjęcie zostało zmodyfikowane, zastosowanie mają również warunki dotyczące zmian i ewentualnego ShareAlike.</p><p><b>Przepisy i dane.</b> Czasy, wartości odżywcze i koszty mają charakter orientacyjny. Informacje na stronie nie zastępują profesjonalnej porady dietetycznej ani medycznej.</p><p><b>Analityka.</b> Strona może korzystać z Google Analytics do zbiorczych statystyk odwiedzin. Ustawienia prywatności i blokowania plików cookie można kontrolować również w przeglądarce.</p><div class="legalLinks"><a href="https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia" target="_blank" rel="noopener noreferrer">Zasady Wikimedia Commons</a><a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Licencja Unsplash</a><a href="https://creativecommons.org/share-your-work/cclicenses/" target="_blank" rel="noopener noreferrer">Creative Commons</a></div><p class="legalSmall">Informacja ma charakter organizacyjny i nie stanowi porady prawnej. Status licencji należy oceniać dla konkretnego materiału.</p></div>`;
 document.body.appendChild(box);
 const style=document.createElement('style');style.textContent=`#legalPanel{position:fixed;inset:0;z-index:20000;background:#1b110deb;padding:24px;overflow:auto}#legalPanel[hidden]{display:none}.legalIn{position:relative;width:min(820px,100%);margin:30px auto;background:#fff9ef;border:1px solid #d4b28d;border-radius:20px;padding:38px;color:#3b2a21;box-shadow:0 35px 100px #0007}.legalIn h2{font:700 46px/1 'Cormorant Garamond',Georgia,serif;margin:10px 0 22px}.legalIn p{line-height:1.7;color:#665247}.legalLinks{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}.legalLinks a{padding:10px 13px;border:1px solid #b98767;border-radius:9px;color:#703b29;text-decoration:none;font-weight:800}.legalSmall{font-size:12px}.legalIn #legalClose{position:absolute;right:14px;top:14px;width:42px;height:42px;border-radius:50%;border:1px solid #d4b28d;background:#fff;color:#3b2a21;font-size:25px}#legalOpen{position:fixed;right:16px;bottom:16px;z-index:15000;border:1px solid #b98767;background:#2c201a;color:#f6e7d4;border-radius:999px;padding:10px 14px;font-weight:800;font-size:11px;box-shadow:0 8px 25px #0003}`;document.head.appendChild(style);
 const open=document.createElement('button');open.id='legalOpen';open.type='button';open.textContent='Informacje prawne';document.body.appendChild(open);open.onclick=()=>box.hidden=false;box.querySelector('#legalClose').onclick=()=>box.hidden=true;box.onclick=e=>{if(e.target===box)box.hidden=true};
}
boot();
})();