// Stołownik — Menu v12
(function(){
function boot(){if(typeof R==='undefined'||!document.getElementById('siteHub'))return setTimeout(boot,120);if(document.getElementById('hubMenu'))return;
const hub=document.getElementById('siteHub'),nav=document.querySelector('.hubLinks');
const menuBtn=document.createElement('button');menuBtn.dataset.go='menu';menuBtn.textContent='Menu';nav?.insertBefore(menuBtn,nav.children[1]||null);
const page=document.createElement('section');page.id='hubMenu';page.className='hubPage';page.hidden=true;page.innerHTML=`<div class="menuHead"><span>MENU STOŁOWNIKA</span><h2>Wybierz coś dobrego.</h2><p>Dania, desery i napoje w jednym, czytelnym menu.</p><div class="menuTabs"><button class="active" data-menu-cat="dania">🍽️ Dania</button><button data-menu-cat="desery">🍰 Desery</button><button data-menu-cat="napoje">🥤 Napoje</button></div></div><div id="menuGrid" class="menuGrid"></div><button id="menuMore" class="menuMore" type="button">Pokaż więcej</button>`;hub.appendChild(page);
let cat='dania',expanded=false;
function desserts(){return R.filter(r=>((r.cats||[]).join(' ')+' '+r.name).toLowerCase().match(/deser|słod|brownie|ciast|pancake|naleś|ryż na mleku|mango sticky|apple pie|placusz/))}
function dishes(){const d=new Set(desserts().map(x=>x.id));return R.filter(r=>!d.has(r.id))}
function drinks(){const src=window.DRINKS||window.drinks||window.D||[];return Array.isArray(src)?src:[]}
function items(){return cat==='desery'?desserts():cat==='napoje'?drinks():dishes()}
function render(){const all=items(),show=expanded?all:all.slice(0,10),grid=document.getElementById('menuGrid');grid.innerHTML=show.map((r,i)=>{const name=r.name||r.n||r.title||'Napój';const img=r.img||r.image||'';const time=r.time||r.minutes||'';return `<button class="menuCard" ${cat==='napoje'?`data-menu-drink="${i}"`:`data-recipe="${r.id}"`}><div class="menuPic">${img?`<img src="${img}" alt="${name}" loading="lazy">`:'<span>Stołownik</span>'}</div><div><small>${cat==='napoje'?'NAPÓJ':(r.flag||'🍽️')+' '+(r.country||'')}</small><b>${name}</b>${time?`<em>${time} min</em>`:''}</div></button>`}).join('');const more=document.getElementById('menuMore');more.hidden=all.length<=10;more.textContent=expanded?'Zwiń menu':`Pokaż pozostałe (${Math.max(0,all.length-10)})`}
page.addEventListener('click',e=>{const t=e.target.closest('[data-menu-cat]');if(t){cat=t.dataset.menuCat;expanded=false;page.querySelectorAll('[data-menu-cat]').forEach(b=>b.classList.toggle('active',b===t));render();return}const card=e.target.closest('[data-recipe]');if(card&&typeof openRecipe==='function')openRecipe(+card.dataset.recipe)});document.getElementById('menuMore').onclick=()=>{expanded=!expanded;render();document.querySelector('.menuHead')?.scrollIntoView({behavior:'smooth',block:'start'})};
menuBtn.addEventListener('click',()=>{document.querySelectorAll('#siteHub>.hubPage').forEach(x=>x.hidden=x!==page);document.querySelectorAll('.hubLinks button').forEach(x=>x.classList.toggle('active',x===menuBtn));render();window.scrollTo({top:0,behavior:'smooth'})});
const style=document.createElement('style');style.textContent=`.menuHead{padding:58px 38px 30px;background:linear-gradient(125deg,#33231d,#65412d);color:#fff}.menuHead>span{font-size:10px;font-weight:800;letter-spacing:.18em;color:#e0ad82}.menuHead h2{font-size:58px!important;margin:9px 0!important;color:#fff3e2!important}.menuHead p{color:#dec8b4}.menuTabs{display:flex;gap:8px;margin-top:25px;flex-wrap:wrap}.menuTabs button{border:1px solid #a47a5e;background:#ffffff0d;color:#f7e6d4;padding:11px 17px;border-radius:999px;font-weight:800}.menuTabs button.active{background:#9a4d30;border-color:#b86542;color:#fff}.menuGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;padding:28px 38px 18px;background:#fffaf1}.menuCard{display:grid;grid-template-columns:118px 1fr;gap:16px;align-items:center;text-align:left;padding:0;border:1px solid #dec6a8;border-radius:13px;background:#f7ead9;overflow:hidden;min-height:112px}.menuPic{height:100%;min-height:112px;background:#ead7bf;display:grid;place-items:center;color:#75523d;font-family:Georgia,serif}.menuPic img{width:100%;height:112px;object-fit:cover;display:block}.menuCard small{display:block;color:#966044;font-size:10px;font-weight:800}.menuCard b{display:block;font:700 24px/1.05 'Cormorant Garamond',serif;color:#35241d;margin:5px 0}.menuCard em{font-style:normal;color:#806b5c;font-size:11px}.menuMore{display:block;margin:8px auto 36px;border:1px solid #8e4a31;background:#8e4a31;color:#fff;padding:13px 22px;border-radius:10px;font-weight:800}.menuMore[hidden]{display:none}@media(max-width:700px){.menuHead{padding:38px 18px 24px}.menuHead h2{font-size:43px!important}.menuGrid{grid-template-columns:1fr;padding:18px 14px}.menuCard{grid-template-columns:96px 1fr}.menuPic,.menuPic img{min-height:100px;height:100px}.menuCard b{font-size:21px}}`;document.head.appendChild(style);render()}
boot();
})();