// Stołownik — przywrócone filtry + poprawki zdjęć
(function(){
const COST={1:12,2:15,3:22,4:31,5:30,6:19,7:29,8:18,9:29,10:23,11:28,12:14,13:31,14:43,15:29,16:19,17:27,18:16,19:22,20:42,21:12,22:17,23:13,24:28,25:38};
const FIXIMG={13:'https://upload.wikimedia.org/wikipedia/commons/2/24/Golabki_jacek.jpg',16:'https://upload.wikimedia.org/wikipedia/commons/2/28/Polish_%22Zapiekanka%22.jpg'};
let maxPrice=999,maxKcal=9999,minProtein=0,maxFat=999,maxCarbs=999;
function apply(){if(typeof R==='undefined'||typeof N==='undefined'||typeof draw!=='function')return setTimeout(apply,50);Object.entries(FIXIMG).forEach(([id,url])=>{const r=R.find(x=>x.id===+id);if(r)r.img=url});
let cats=document.getElementById('cats');if(!document.querySelector('.foodfilters')){let st=document.createElement('style');st.textContent='.foodfilters{background:#fff;border:1px solid #ead7bf;border-radius:20px;padding:16px;margin:-8px 0 24px}.foodfilters h3{margin:0 0 11px;font-size:18px}.filterrow{display:flex;gap:9px;flex-wrap:wrap}.filterrow label{display:flex;align-items:center;gap:7px;background:#fffaf3;border:1px solid #ead7bf;border-radius:13px;padding:8px 10px;font-size:13px;font-weight:700}.filterrow select{border:0;background:transparent;color:#365d45;font-weight:800;outline:0}.resetfilters{border:0;border-radius:13px;padding:9px 13px;background:#365d45;color:#fff;font-weight:800}';document.head.appendChild(st);let box=document.createElement('div');box.className='foodfilters';box.innerHTML='<h3>Filtry dania</h3><div class="filterrow"><label>💰 Cena / os. <select id="fprice"><option value="999">dowolna</option><option value="5">do 5 zł</option><option value="10">do 10 zł</option><option value="15">do 15 zł</option><option value="20">do 20 zł</option></select></label><label>🔥 Kalorie <select id="fkcal"><option value="9999">dowolne</option><option value="400">do 400 kcal</option><option value="600">do 600 kcal</option><option value="800">do 800 kcal</option></select></label><label>💪 Białko <select id="fprotein"><option value="0">dowolne</option><option value="20">min. 20 g</option><option value="30">min. 30 g</option><option value="40">min. 40 g</option></select></label><label>🥑 Tłuszcz <select id="ffat"><option value="999">dowolny</option><option value="15">do 15 g</option><option value="25">do 25 g</option><option value="35">do 35 g</option></select></label><label>🌾 Węglowodany <select id="fcarb"><option value="999">dowolne</option><option value="40">do 40 g</option><option value="60">do 60 g</option><option value="80">do 80 g</option></select></label><button class="resetfilters" id="freset">Wyczyść filtry</button></div>';cats.insertAdjacentElement('afterend',box)}
const originalFilt=window.filt;if(originalFilt&&!window.__filtersRestored){window.__filtersRestored=true;window.filt=function(){return originalFilt().filter(r=>{let n=N[r.id]||[0,0,0,0,0],price=(COST[r.id]||0)/2;return price<=maxPrice&&n[0]<=maxKcal&&n[1]>=minProtein&&n[2]<=maxFat&&n[3]<=maxCarbs})}}
function bind(id,set){let e=document.getElementById(id);if(e)e.onchange=x=>{set(+x.target.value);draw()}}bind('fprice',v=>maxPrice=v);bind('fkcal',v=>maxKcal=v);bind('fprotein',v=>minProtein=v);bind('ffat',v=>maxFat=v);bind('fcarb',v=>maxCarbs=v);let reset=document.getElementById('freset');if(reset)reset.onclick=()=>{maxPrice=999;maxKcal=9999;minProtein=0;maxFat=999;maxCarbs=999;['fprice','fkcal','fprotein','ffat','fcarb'].forEach(id=>document.getElementById(id).selectedIndex=0);draw()};draw()}
apply();
})();