// Stołownik — własne zakresy filtrów + poprawki zdjęć
(function(){
const COST={1:12,2:15,3:22,4:31,5:30,6:19,7:29,8:18,9:29,10:23,11:28,12:14,13:31,14:43,15:29,16:19,17:27,18:16,19:22,20:42,21:12,22:17,23:13,24:28,25:38};
const FIXIMG={13:'https://upload.wikimedia.org/wikipedia/commons/2/24/Golabki_jacek.jpg',16:'https://upload.wikimedia.org/wikipedia/commons/2/28/Polish_%22Zapiekanka%22.jpg'};
let state={};
function num(id,fallback){let e=document.getElementById(id),v=e&&e.value.trim();return v===''?fallback:+v}
function apply(){if(typeof R==='undefined'||typeof draw!=='function'||typeof filt!=='function')return setTimeout(apply,50);Object.entries(FIXIMG).forEach(([id,url])=>{let r=R.find(x=>x.id===+id);if(r)r.img=url});
if(!document.getElementById('advancedFilters')){let st=document.createElement('style');st.textContent='.foodfilters{background:#fff;border:1px solid #e7d8c5;border-radius:22px;padding:18px;margin:0 0 25px;box-shadow:0 10px 25px #6246220c}.filtertop{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.filtertop h3{margin:0;font-size:22px}.filtergrid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.filterbox{background:#fff8ec;border:1px solid #e7d8c5;border-radius:15px;padding:10px 12px}.filterbox>span{display:block;font-size:12px;color:#756c63;font-weight:800;margin-bottom:7px}.range{display:grid;grid-template-columns:1fr auto 1fr;gap:7px;align-items:center}.range input{width:100%;min-width:0;border:1px solid #dfd0bd;background:#fff;border-radius:10px;padding:9px;font-weight:800;color:#365d45}.range i{font-style:normal;color:#756c63;font-size:12px}.filterhint{margin:10px 0 0;color:#756c63;font-size:12px}.resetfilters{border:0;border-radius:12px;padding:10px 14px;background:#9b382b;color:#fff;font-weight:800}@media(max-width:760px){.filtergrid{grid-template-columns:1fr 1fr}}@media(max-width:500px){.filtergrid{grid-template-columns:1fr}}';document.head.appendChild(st);let box=document.createElement('div');box.id='advancedFilters';box.className='foodfilters';let f=(icon,title,id,unit,step='1')=>'<label class="filterbox"><span>'+icon+' '+title+' ('+unit+')</span><div class="range"><input type="number" min="0" step="'+step+'" id="'+id+'Min" placeholder="od"><i>—</i><input type="number" min="0" step="'+step+'" id="'+id+'Max" placeholder="do"></div></label>';box.innerHTML='<div class="filtertop"><h3>Filtry dań — ustaw po swojemu</h3><button class="resetfilters" id="freset">Wyczyść wszystko</button></div><div class="filtergrid">'+f('💰','Cena za osobę','price','zł','0.5')+f('🔥','Kalorie / porcja','kcal','kcal')+f('⏱','Czas przygotowania','time','min')+f('💪','Białko / porcja','protein','g')+f('🥑','Tłuszcz / porcja','fat','g')+f('🌾','Węglowodany / porcja','carbs','g')+'</div><p class="filterhint">Możesz wpisać tylko „od”, tylko „do” albo pełny zakres. Puste pole = bez limitu.</p>';document.getElementById('cats').insertAdjacentElement('afterend',box)}
if(!window.__rangeFilters){window.__rangeFilters=true;let baseFilt=window.filt;window.filt=function(){return baseFilt().filter(r=>{let n=(typeof N!=='undefined'&&N[r.id])||[0,0,0,0,0],vals={price:(COST[r.id]||0)/2,kcal:n[0],time:r.time,protein:n[1],fat:n[2],carbs:n[3]};return Object.keys(vals).every(k=>vals[k]>=num(k+'Min',-Infinity)&&vals[k]<=num(k+'Max',Infinity))})}}
['price','kcal','time','protein','fat','carbs'].forEach(k=>['Min','Max'].forEach(s=>{let e=document.getElementById(k+s);e.addEventListener('input',draw)}));document.getElementById('freset').onclick=()=>{document.querySelectorAll('#advancedFilters input').forEach(e=>e.value='');draw()};draw()}
apply();
})();