// Stołownik — filtry, porcje, ceny i poprawki zdjęć
(function(){
const COST={1:12,2:15,3:22,4:31,5:30,6:19,7:29,8:18,9:29,10:23,11:28,12:14,13:31,14:43,15:29,16:19,17:27,18:16,19:22,20:42,21:12,22:17,23:13,24:28,25:38};
const FIXIMG={13:'https://www.polana.com/cdn/shop/files/POLISH_Golabki_-_Stuffed_Cabbage_with_Rice_Mushroom_Topped_with_Tomato_Sauce.png?v=1751050224',16:'https://i.lezzet.com.tr/images-xxlarge-recipe/zapiekanka-9540b125-2c23-4cd2-947c-3cfc00efce10.jpg'};
let maxPrice=999,maxKcal=9999,minProtein=0,maxFat=999,maxCarbs=999;
function apply(){if(typeof R==='undefined'||typeof N==='undefined')return setTimeout(apply,50);Object.entries(FIXIMG).forEach(([id,url])=>{let r=R.find(x=>x.id===+id);if(r)r.img=url});
let st=document.createElement('style');st.textContent=`.cats{gap:10px!important}.cat{border:1px solid #ead7bf!important;background:linear-gradient(180deg,#fff,#fffaf3)!important;border-radius:16px!important;padding:10px 14px!important;font-weight:700;box-shadow:0 3px 10px #60401b0c;transition:.18s}.cat:hover{transform:translateY(-2px);border-color:#b86550!important;box-shadow:0 7px 16px #60401b18}.cat.active{background:linear-gradient(135deg,#a73d2e,#c45d43)!important;color:#fff!important;border-color:transparent!important;box-shadow:0 7px 16px #9b382b30}.cat b{display:inline-grid;place-items:center;min-width:23px;height:23px;margin-left:5px;padding:0 6px;border-radius:9px;background:#f3eadc;color:#365d45}.cat.active b{background:#fff2;color:#fff}.foodfilters{background:#fff;border:1px solid #ead7bf;border-radius:20px;padding:16px;margin:-8px 0 24px;box-shadow:0 8px 24px #60401b0c}.foodfilters h3{margin:0 0 11px;font-size:18px}.filterrow{display:flex;gap:9px;flex-wrap:wrap}.filterrow label{display:flex;align-items:center;gap:7px;background:#fffaf3;border:1px solid #ead7bf;border-radius:13px;padding:8px 10px;font-size:13px;font-weight:700}.filterrow select{border:0;background:transparent;color:#365d45;font-weight:800;outline:0}.resetfilters{border:0;border-radius:13px;padding:9px 13px;background:#365d45;color:white;font-weight:800}.portion-input{width:90px;padding:8px 10px;border:1px solid #d9c8b3;border-radius:10px;background:#fff}.costbox{background:#fff;border:1px solid #d9c8b3;border-radius:12px;padding:8px 12px;font-weight:800;color:#365d45}`;document.head.appendChild(st);
let cats=document.getElementById('cats');let box=document.createElement('div');box.className='foodfilters';box.innerHTML=`<h3>Filtry dania</h3><div class="filterrow"><label>💰 Cena / os. <select id="fprice"><option value="999">dowolna</option><option value="5">do 5 zł</option><option value="10">do 10 zł</option><option value="15">do 15 zł</option><option value="20">do 20 zł</option></select></label><label>🔥 Kalorie <select id="fkcal"><option value="9999">dowolne</option><option value="400">do 400 kcal</option><option value="600">do 600 kcal</option><option value="800">do 800 kcal</option></select></label><label>💪 Białko <select id="fprotein"><option value="0">dowolne</option><option value="20">min. 20 g</option><option value="30">min. 30 g</option><option value="40">min. 40 g</option></select></label><label>🥑 Tłuszcz <select id="ffat"><option value="999">dowolny</option><option value="15">do 15 g</option><option value="25">do 25 g</option><option value="35">do 35 g</option></select></label><label>🌾 Węglowodany <select id="fcarb"><option value="999">dowolne</option><option value="40">do 40 g</option><option value="60">do 60 g</option><option value="80">do 80 g</option></select></label><button class="resetfilters" id="freset">Wyczyść filtry</button></div>`;cats.insertAdjacentElement('afterend',box);
const baseFilt=window.filt;window.filt=function(){return baseFilt().filter(r=>{let n=N[r.id]||[0,0,0,0,0],price=(COST[r.id]||0)/2;return price<=maxPrice&&n[0]<=maxKcal&&n[1]>=minProtein&&n[2]<=maxFat&&n[3]<=maxCarbs})};function bind(id,fn){document.getElementById(id).onchange=e=>{fn(+e.target.value);draw()}}bind('fprice',v=>maxPrice=v);bind('fkcal',v=>maxKcal=v);bind('fprotein',v=>minProtein=v);bind('ffat',v=>maxFat=v);bind('fcarb',v=>maxCarbs=v);document.getElementById('freset').onclick=()=>{maxPrice=999;maxKcal=9999;minProtein=0;maxFat=999;maxCarbs=999;['fprice','fkcal','fprotein','ffat','fcarb'].forEach(id=>document.getElementById(id).selectedIndex=0);draw()};
const baseOpen=window.openR;window.openR=function(id){baseOpen(id);setTimeout(()=>{let old=document.getElementById('portions');if(old&&old.tagName==='SELECT'){let inp=document.createElement('input');inp.type='number';inp.id='portions';inp.className='portion-input';inp.min='1';inp.max='50';inp.value='2';inp.oninput=()=>renderRecipe();old.replaceWith(inp)}let bar=document.querySelector('.recipebar');if(bar&&!document.getElementById('cost')){let c=document.createElement('span');c.id='cost';c.className='costbox';bar.appendChild(c)}renderRecipe()},0)};const baseRender=window.renderRecipe;window.renderRecipe=function(){baseRender();if(!current)return;let p=Math.max(1,parseInt(document.getElementById('portions')?.value)||2),c=document.getElementById('cost');if(c){let total=(COST[current.id]||0)*p/2;c.textContent=`Cena orientacyjna: ${total.toFixed(2).replace('.',',')} zł · ${(total/p).toFixed(2).replace('.',',')} zł/os.`}};drawCats();draw()}
apply();})();