// Stołownik: 25 nowych przepisów (26–50)
(function(){
function add(){if(typeof R==='undefined'||typeof N==='undefined'||typeof M==='undefined')return setTimeout(add,80);if(R.some(r=>r.id===26))return;
const X=[
[26,'Omlet z warzywami',['Śniadania','Wegetariańskie','Szybkie'],15,'Puszysty omlet z papryką, pomidorem i szczypiorkiem.',['4 jajka','1/2 papryki','1 pomidor','2 łyżki szczypiorku','1 łyżeczka masła','sól i pieprz'],['Warzywa pokrój drobno.','Jajka roztrzep z solą i pieprzem.','Na maśle podsmaż paprykę 3 minuty.','Dodaj pomidora i wlej jajka.','Smaż pod przykryciem na małym ogniu do ścięcia.'],[390,27,25,10,3]],
[27,'Pasta jajeczna z pieczywem',['Śniadania','Wegetariańskie','Szybkie'],15,'Kremowa pasta jajeczna ze szczypiorkiem i musztardą.',['4 jajka','2 łyżki jogurtu greckiego','1 łyżeczka musztardy','2 łyżki szczypiorku','4 kromki pieczywa','sól i pieprz'],['Jajka ugotuj na twardo.','Obierz i rozgnieć widelcem.','Dodaj jogurt, musztardę i szczypiorek.','Dopraw solą i pieprzem.','Podawaj na świeżym lub podpieczonym pieczywie.'],[430,25,18,43,5]],
[28,'Kanapki z twarożkiem i rzodkiewką',['Śniadania','Wegetariańskie','Szybkie'],10,'Proste kanapki z kremowym twarożkiem i chrupiącą rzodkiewką.',['200 g twarogu','3 łyżki jogurtu naturalnego','6 rzodkiewek','2 łyżki szczypiorku','4 kromki chleba','sól i pieprz'],['Twaróg rozgnieć z jogurtem.','Rzodkiewki pokrój w plasterki.','Dodaj szczypiorek i dopraw.','Posmaruj pieczywo twarożkiem.','Na wierzchu ułóż rzodkiewkę.'],[410,28,12,48,7]],
[29,'Zupa krem z dyni',['Zupy','Obiady','Wegetariańskie'],40,'Aksamitny krem dyniowy z imbirem i delikatną śmietanką.',['700 g dyni','1 ziemniak','1 marchew','1 cebula','800 ml bulionu warzywnego','1 cm imbiru','2 łyżki śmietanki','1 łyżka oliwy'],['Cebulę podsmaż na oliwie.','Dodaj pokrojoną dynię, ziemniaka, marchew i imbir.','Wlej bulion i gotuj około 25 minut.','Zmiksuj na gładki krem.','Dodaj śmietankę i dopraw.'],[330,8,13,49,9]],
[30,'Krem brokułowy z grzankami',['Zupy','Obiady','Wegetariańskie'],30,'Lekki krem z brokułów z chrupiącymi grzankami.',['1 duży brokuł','1 ziemniak','1 cebula','750 ml bulionu','2 łyżki jogurtu','4 kromki pieczywa','1 łyżka oliwy'],['Cebulę zeszklij na oliwie.','Dodaj ziemniaka i bulion, gotuj 10 minut.','Dodaj brokuł i gotuj kolejne 10 minut.','Zmiksuj i dodaj jogurt.','Pieczywo podpiecz i podaj jako grzanki.'],[350,14,11,52,10]],
[31,'Krupnik domowy',['Zupy','Obiady','Polskie klasyki'],60,'Syty krupnik z kaszą jęczmienną i dużą porcją warzyw.',['100 g kaszy jęczmiennej','2 ziemniaki','2 marchewki','1 pietruszka','1/4 selera','1,2 l bulionu','1 liść laurowy','natka pietruszki'],['Warzywa obierz i pokrój.','Bulion zagotuj z liściem laurowym.','Dodaj kaszę i warzywa.','Gotuj na małym ogniu około 40 minut.','Dopraw i posyp natką.'],[390,14,9,68,10]],
[32,'Fasolka po bretońsku',['Obiady','Mięsne','Polskie klasyki','Jednogarnkowe'],70,'Gęsta fasolka w pomidorowym sosie z kiełbasą i majerankiem.',['500 g ugotowanej białej fasoli','250 g kiełbasy','1 cebula','500 ml passaty','1 łyżka koncentratu','1 łyżeczka majeranku','1 liść laurowy'],['Kiełbasę pokrój i zrumień.','Dodaj cebulę i smaż 4 minuty.','Dodaj passatę, koncentrat i przyprawy.','Wsyp fasolę i wymieszaj.','Duś około 35 minut na małym ogniu.'],[680,34,29,69,14]],
[33,'Bigos domowy',['Obiady','Mięsne','Polskie klasyki','Jednogarnkowe'],120,'Klasyczny bigos z kapustą kiszoną, mięsem i suszonymi śliwkami.',['700 g kapusty kiszonej','250 g łopatki wieprzowej','180 g kiełbasy','1 cebula','5 suszonych śliwek','2 liście laurowe','ziele angielskie','1 łyżka koncentratu'],['Kapustę posiekaj i włóż do garnka.','Mięso i kiełbasę zrumień z cebulą.','Dodaj do kapusty razem z przyprawami.','Dodaj śliwki i koncentrat.','Duś powoli około 90 minut, mieszając.'],[720,43,38,48,11]],
[34,'Kopytka z masłem i bułką tartą',['Obiady','Wegetariańskie','Polskie klasyki'],55,'Miękkie ziemniaczane kopytka z rumianą bułką tartą.',['600 g ugotowanych ziemniaków','150 g mąki pszennej','1 jajko','1 łyżka mąki ziemniaczanej','2 łyżki masła','3 łyżki bułki tartej'],['Ziemniaki przeciśnij przez praskę i wystudź.','Dodaj jajko i mąki, krótko zagnieć.','Uformuj wałki i pokrój ukośnie.','Gotuj około 2 minuty od wypłynięcia.','Masło zrumień z bułką tartą i polej kopytka.'],[610,17,19,96,6]],
[35,'Makaron z kurczakiem i szpinakiem',['Obiady','Mięsne','Makarony'],35,'Kremowy makaron z soczystym kurczakiem, szpinakiem i czosnkiem.',['220 g makaronu','300 g piersi kurczaka','150 g szpinaku','2 ząbki czosnku','150 ml śmietanki 18%','30 g parmezanu','1 łyżka oliwy'],['Makaron ugotuj al dente.','Kurczaka pokrój i zrumień na oliwie.','Dodaj czosnek i szpinak.','Wlej śmietankę i dodaj parmezan.','Wymieszaj z makaronem i dopraw.'],[760,50,30,78,6]],
[36,'Makaron z pesto i pomidorkami',['Obiady','Wegetariańskie','Makarony','Szybkie'],20,'Szybki makaron z bazyliowym pesto i słodkimi pomidorkami.',['220 g makaronu','4 łyżki pesto bazyliowego','200 g pomidorków koktajlowych','30 g parmezanu','1 łyżka oliwy','garść rukoli'],['Makaron ugotuj al dente.','Pomidorki przekrój i krótko podsmaż.','Odlej trochę wody z makaronu.','Połącz makaron z pesto i odrobiną wody.','Dodaj pomidorki, rukolę i parmezan.'],[690,21,28,87,7]],
[37,'Ryż smażony z kurczakiem',['Obiady','Mięsne','Szybkie'],25,'Szybki ryż z kurczakiem, jajkiem i warzywami z jednej patelni.',['300 g ugotowanego ryżu','250 g piersi kurczaka','2 jajka','200 g mieszanki warzyw','2 łyżki sosu sojowego','1 łyżka oleju'],['Kurczaka pokrój i usmaż.','Dodaj warzywa i smaż 4 minuty.','Przesuń składniki na bok i zetnij jajka.','Dodaj zimny ugotowany ryż.','Wlej sos sojowy i smaż jeszcze 3 minuty.'],[650,43,21,74,6]],
[38,'Pulpeciki w sosie pomidorowym',['Obiady','Mięsne'],50,'Delikatne pulpeciki w aromatycznym sosie pomidorowym.',['400 g mięsa mielonego','1 jajko','3 łyżki bułki tartej','1 cebula','500 ml passaty','1 ząbek czosnku','1 łyżka oliwy','oregano'],['Mięso wymieszaj z jajkiem i bułką tartą.','Uformuj niewielkie pulpeciki.','Obsmaż je krótko na oliwie.','Dodaj cebulę, czosnek i passatę.','Duś pod przykryciem około 25 minut.'],[590,42,28,42,5]],
[39,'Kurczak w sosie pieczarkowym',['Obiady','Mięsne'],40,'Soczysty kurczak w kremowym sosie z dużą ilością pieczarek.',['350 g piersi kurczaka','300 g pieczarek','1 cebula','150 ml śmietanki 18%','1 łyżka oliwy','1 łyżeczka musztardy','natka pietruszki'],['Kurczaka pokrój, dopraw i zrumień.','Zdejmij mięso, a na patelnię dodaj cebulę i pieczarki.','Smaż aż pieczarki odparują.','Dodaj śmietankę i musztardę.','Włóż kurczaka i duś 8 minut.'],[570,48,31,20,4]],
[40,'Dorsz pieczony z warzywami',['Obiady','Ryby','Z piekarnika'],40,'Lekki dorsz pieczony z cukinią, papryką i cytryną.',['400 g filetu z dorsza','1 cukinia','1 papryka','1 cebula','1/2 cytryny','1 łyżka oliwy','koperek','sól i pieprz'],['Piekarnik nagrzej do 200°C.','Warzywa pokrój i przełóż do naczynia.','Skrop oliwą i piecz 12 minut.','Dodaj doprawionego dorsza i plasterki cytryny.','Piecz jeszcze około 15 minut i posyp koperkiem.'],[430,48,17,25,7]],
[41,'Sałatka z kurczakiem i sosem jogurtowym',['Obiady','Kolacje','Mięsne','Sałatki','Szybkie'],25,'Duża chrupiąca sałatka z kurczakiem i lekkim sosem jogurtowym.',['300 g piersi kurczaka','1 sałata rzymska','1 pomidor','1 ogórek','1/2 czerwonej cebuli','150 g jogurtu','1 ząbek czosnku','1 łyżka oliwy'],['Kurczaka dopraw i usmaż.','Warzywa umyj i pokrój.','Jogurt wymieszaj z czosnkiem i przyprawami.','Kurczaka pokrój w paski.','Połącz składniki i polej sosem.'],[470,46,19,28,8]],
[42,'Sałatka z tuńczykiem i jajkiem',['Kolacje','Ryby','Sałatki','Szybkie'],15,'Syta sałatka z tuńczykiem, jajkiem i świeżymi warzywami.',['1 puszka tuńczyka w sosie własnym','2 jajka','1 pomidor','1/2 ogórka','garść sałaty','1/2 czerwonej cebuli','1 łyżka oliwy','sok z cytryny'],['Jajka ugotuj na twardo.','Warzywa pokrój i ułóż na sałacie.','Tuńczyka odsącz.','Dodaj ćwiartki jajek i tuńczyka.','Skrop oliwą i cytryną, dopraw.'],[420,39,24,15,5]],
[43,'Tortilla z kurczakiem i warzywami',['Obiady','Kolacje','Mięsne','Szybkie'],25,'Domowa tortilla z kurczakiem, chrupiącymi warzywami i sosem.',['2 duże tortille','300 g piersi kurczaka','1/2 papryki','1 pomidor','garść sałaty','100 g jogurtu','1 ząbek czosnku','1 łyżka oleju'],['Kurczaka pokrój, dopraw i usmaż.','Warzywa pokrój w paski.','Jogurt połącz z czosnkiem.','Tortille podgrzej na suchej patelni.','Nałóż składniki, polej sosem i ciasno zawiń.'],[620,45,21,67,7]],
[44,'Quesadilla z serem i warzywami',['Kolacje','Wegetariańskie','Szybkie'],20,'Chrupiąca tortilla z ciągnącym serem, papryką i kukurydzą.',['2 tortille','160 g sera cheddar lub gouda','1/2 papryki','80 g kukurydzy','1/2 czerwonej cebuli','2 łyżki jogurtu'],['Warzywa drobno pokrój.','Na połowie każdej tortilli rozłóż ser i warzywa.','Złóż tortille na pół.','Smaż na suchej patelni po 2–3 minuty z każdej strony.','Pokrój w trójkąty i podaj z jogurtem.'],[670,28,31,68,6]],
[45,'Ziemniaki zapiekane z brokułem i serem',['Obiady','Wegetariańskie','Z piekarnika'],55,'Rumiane ziemniaki z brokułem pod warstwą ciągnącego sera.',['600 g ziemniaków','1 brokuł','180 g sera','150 ml śmietanki 12%','1 ząbek czosnku','1 łyżeczka masła','sól i pieprz'],['Ziemniaki podgotuj 10 minut i pokrój.','Brokuł podziel na różyczki i obgotuj 3 minuty.','Naczynie posmaruj masłem i czosnkiem.','Ułóż ziemniaki i brokuł, polej śmietanką.','Posyp serem i piecz około 25 minut w 200°C.'],[640,27,31,66,9]],
[46,'Chili sin carne',['Obiady','Wegetariańskie','Jednogarnkowe'],40,'Pikantne, sycące chili z fasolą, kukurydzą i pomidorami.',['1 puszka czerwonej fasoli','1 puszka krojonych pomidorów','150 g kukurydzy','1 papryka','1 cebula','2 ząbki czosnku','1 łyżka oliwy','papryka wędzona i chili'],['Cebulę i paprykę podsmaż na oliwie.','Dodaj czosnek i przyprawy.','Dodaj pomidory, fasolę i kukurydzę.','Duś około 25 minut.','Dopraw do smaku i podaj samodzielnie lub z ryżem.'],[470,20,10,77,17]],
[47,'Placuszki bananowe',['Śniadania','Wegetariańskie','Na słodko','Szybkie'],20,'Miękkie placuszki bananowe dobre na szybkie śniadanie.',['2 dojrzałe banany','2 jajka','100 g mąki','1/2 łyżeczki proszku do pieczenia','1 łyżeczka oleju','100 g jogurtu','garść owoców'],['Banany rozgnieć widelcem.','Dodaj jajka i wymieszaj.','Wsyp mąkę z proszkiem do pieczenia.','Smaż małe placuszki na lekko natłuszczonej patelni.','Podaj z jogurtem i owocami.'],[520,18,16,78,7]],
[48,'Ryż na mleku z jabłkiem i cynamonem',['Śniadania','Wegetariańskie','Na słodko'],30,'Kremowy ryż na mleku z ciepłym jabłkiem i cynamonem.',['160 g ryżu','600 ml mleka','2 jabłka','1 łyżeczka cynamonu','1 łyżka miodu','1 łyżeczka masła'],['Ryż przepłucz i zalej mlekiem.','Gotuj powoli około 20 minut, mieszając.','Jabłka pokrój i podsmaż na maśle.','Dodaj cynamon i miód.','Ryż podaj z ciepłymi jabłkami.'],[550,15,13,96,6]],
[49,'Brownie czekoladowe',['Desery','Wegetariańskie','Na słodko','Z piekarnika'],45,'Wilgotne, mocno czekoladowe brownie z prostych składników.',['180 g gorzkiej czekolady','150 g masła','3 jajka','150 g cukru','100 g mąki','2 łyżki kakao','szczypta soli'],['Piekarnik nagrzej do 175°C.','Czekoladę rozpuść z masłem i lekko przestudź.','Jajka wymieszaj z cukrem.','Dodaj czekoladę, mąkę, kakao i sól.','Piecz około 25 minut; środek powinien zostać wilgotny.'],[590,8,36,64,4]],
[50,'Koktajl bowl z owocami i owsianką',['Śniadania','Wegetariańskie','Na słodko','Szybkie'],10,'Gęsty owocowy bowl z bananem, jogurtem i płatkami owsianymi.',['2 banany','200 g mrożonych owoców jagodowych','200 g jogurtu naturalnego','80 g płatków owsianych','1 łyżka masła orzechowego','1 łyżka pestek'],['Jednego banana zmiksuj z owocami i jogurtem.','Przelej gęsty koktajl do misek.','Drugiego banana pokrój.','Dodaj płatki, banana i pestki.','Na wierzch dodaj masło orzechowe.'],[510,18,17,76,11]]
];
const imgs={26:'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1200&q=80',27:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',28:'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=1200&q=80',29:'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',30:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',31:'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',32:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',33:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',34:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',35:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',36:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',37:'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80',38:'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1200&q=80',39:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1200&q=80',40:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',41:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',42:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80',43:'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80',44:'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80',45:'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=1200&q=80',46:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',47:'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80',48:'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=1200&q=80',49:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80',50:'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80'};
X.forEach(x=>{R.push({id:x[0],name:x[1],cats:x[2],time:x[3],img:imgs[x[0]],desc:x[4],ingredients:x[5],steps:x[6]});N[x[0]]=x[7];M[x[0]]=x[6].map((_,i)=>Math.max(1,Math.round(x[3]/x[6].length)));});
if(typeof cats!=='undefined'){X.forEach(x=>x[2].forEach(c=>{if(!cats.includes(c))cats.push(c)}));}
if(typeof renderCats==='function')renderCats();if(typeof filt==='function')filt();if(document.getElementById('heroCount'))document.getElementById('heroCount').textContent=R.length;
}
add();
})();