// Stołownik — restauracyjny portal v8: rozdzielone widoki jedzenia i napojów
(function(){
function boot(){
  if(typeof R==='undefined'||!document.querySelector('main'))return setTimeout(boot,120);
  document.getElementById('siteHub')?.remove();
  const main=document.querySelector('main');
  [...main.children].forEach(x=>x.dataset.original='1');

  if(!document.getElementById('stolownikFonts')){const l=document.createElement('link');l.id='stolownikFonts';l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap';document.head.appendChild(l)}
  const hub=document.createElement('div');hub.id='siteHub';
  const wanted=['Spaghetti bolognese','Sałatka grecka','Kurczak curry','Quesadilla z serem i warzywami','Zupa krem z dyni','Łosoś pieczony'];
  const picks=wanted.map(n=>R.find(r=>r.name===n)).filter(Boolean);R.forEach(r=>{if(picks.length<6&&!picks.includes(r))picks.push(r)});const hero=picks.slice(0,3);
  hub.innerHTML=`<nav class="hubNav" aria-label="Główna nawigacja"><button class="hubBrand" data-go="home"><span>Stołownik</span><small>kuchnia bez granic</small></button><div class="hubLinks"><button data-go="home">Start</button><button data-go="food">Przepisy</button><button data-go="drinks">Napoje</button><button data-go="gallery">Galeria</button><button data-go="story">O nas</button></div></nav><section id="hubHome" class="hubPage"><section class="restaurantHero"><div class="heroCopy"><span class="eyebrow">JESIENNY STÓŁ · SMAKI ŚWIATA</span><h1>Smaki, do których chce się wracać.</h1><p>Przepisy z różnych stron świata podane po polsku — czytelnie, apetycznie i bez zbędnego chaosu.</p><div class="heroActions"><button data-go="food">Odkryj przepisy</button><button class="ghost" data-go="drinks">Zobacz napoje</button></div></div><div class="heroMosaic">${hero.map((r,i)=>`<button class="heroPhoto heroPhoto${i+1}" data-recipe="${r.id}"><img src="${r.img}" alt="${r.name}"><span><b>${r.name}</b><small>${r.time} min</small></span></button>`).join('')}</div></section><section class="quickSection"><div class="sectionIntro"><span class="eyebrow">WSZYSTKO POD RĘKĄ</span><h2>Wybierz, na co masz dziś ochotę</h2></div><div class="hubTiles"><button data-go="food"><b>Przepisy</b><em>Wszystkie dania.</em></button><button data-go="drinks"><b>Napoje</b><em>Domowe napoje na zimno i ciepło.</em></button><button data-go="gallery"><b>Galeria</b><em>Wybieraj dania oczami.</em></button><button data-go="story"><b>O nas</b><em>Poznaj Stołownik.</em></button></div></section></section><section id="hubGallery" class="hubPage" hidden><div class="sectionTitle galleryTitle"><span class="eyebrow">GALERIA</span><h2>Najpierw jedzą oczy</h2></div><div class="galleryGrid">${R.slice(0,24).map(r=>`<button data-recipe="${r.id}"><img src="${r.img}" alt="${r.name}" loading="lazy"><span>${r.name}</span></button>`).join('')}</div></section><section id="hubStory" class="hubPage" hidden><div class="storyHero"><span class="eyebrow">O STOŁOWNIKU</span><h2>Kuchnia bez granic, po polsku.</h2><p>Stołownik łączy domowe klasyki z inspiracjami z różnych stron świata.</p></div></section>`;
  main.prepend(hub);
  const st=document.createElement('style');st.id='siteHubStyle';st.textContent=`body>header{display:none!important}body{font-family:Manrope,system-ui,sans-serif!important;background:linear-gradient(180deg,#f4eadc,#ead8c1)!important}main{max-width:none!important;padding:0 0 70px!important}#siteHub{max-width:1280px;margin:0 auto 68px;padding:18px 24px 0}.hubNav{position:sticky;top:10px;z-index:40;display:flex;align-items:center;justify-content:space-between;gap:28px;padding:12px 14px 12px 20px;background:#241a16f2;border:1px solid #6d4b37;border-radius:18px;margin-bottom:20px}.hubBrand{border:0;background:transparent;color:#fff3df}.hubBrand span{display:block;font:700 31px/1 'Cormorant Garamond',serif}.hubBrand small{color:#cda887}.hubLinks{display:flex;gap:5px;flex-wrap:wrap}.hubLinks button{border:0;background:transparent;color:#f0dfcb;padding:10px 15px;border-radius:999px;font-weight:700}.hubLinks button.active{background:#8d472f;color:#fff}.hubPage{overflow:hidden;background:#fffaf1;border:1px solid #d7b995;border-radius:22px}.restaurantHero{min-height:600px;display:grid;grid-template-columns:1fr 1fr;gap:45px;align-items:center;padding:60px;background:linear-gradient(125deg,#3a2921,#70452f);color:#fff4e6}.restaurantHero h1,.sectionIntro h2,.storyHero h2{font-family:'Cormorant Garamond',serif;font-size:64px;line-height:.9}.heroActions{display:flex;gap:10px;margin-top:28px}.heroActions button{padding:14px 20px;border-radius:10px;border:1px solid #a96849;background:#93472f;color:#fff;font-weight:800}.heroMosaic{display:grid;grid-template-columns:1fr 1fr;gap:12px}.heroPhoto{position:relative;border:0;padding:0;height:220px;overflow:hidden;border-radius:14px}.heroPhoto img{width:100%;height:100%;object-fit:cover}.heroPhoto span{position:absolute;bottom:0;left:0;right:0;padding:30px 12px 12px;background:linear-gradient(transparent,#211);color:#fff}.quickSection,.galleryTitle,.storyHero{padding:55px 34px}.hubTiles{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.hubTiles button{padding:25px;text-align:left;background:#fffaf1;border:1px solid #dbc1a1;border-radius:14px}.hubTiles b{display:block;font:700 30px 'Cormorant Garamond',serif}.hubTiles em{font-style:normal}.galleryGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;padding:0 34px 48px}.galleryGrid button{padding:0;border:1px solid #dcc4a6;background:#f2e4d2;border-radius:13px;overflow:hidden}.galleryGrid img{width:100%;height:210px;object-fit:cover}.galleryGrid span{display:block;padding:12px}.hubHidden{display:none!important}.drinkOnlyHide{display:none!important}@media(max-width:760px){#siteHub{padding:10px 12px}.hubNav{position:static;flex-direction:column;align-items:flex-start}.restaurantHero{grid-template-columns:1fr;padding:35px 22px}.hubTiles,.galleryGrid{grid-template-columns:1fr 1fr}}`;
  document.head.appendChild(st);
  function originals(show){[...main.children].filter(x=>x.dataset.original==='1').forEach(x=>x.classList.toggle('hubHidden',!show))}
  function hideFoodOutsideHub(hide){const selectors=['.searchbox','.daybox','.section-head','.cats','.count','.grid','.foodfilters','#foodFilters','.foodFilters'];selectors.forEach(sel=>document.querySelectorAll(sel).forEach(x=>{if(!x.closest('#drinkCatalog')&&!x.closest('#siteHub'))x.classList.toggle('drinkOnlyHide',hide)}))}
  function page(name){document.querySelectorAll('.hubPage').forEach(x=>x.hidden=true);document.querySelectorAll('.hubLinks button').forEach(x=>x.classList.toggle('active',x.dataset.go===name));const drinks=document.getElementById('drinkCatalog');if(name==='home'){hideFoodOutsideHub(false);originals(false);drinks?.classList.remove('show');hubHome.hidden=false}if(['gallery','story'].includes(name)){hideFoodOutsideHub(false);originals(false);drinks?.classList.remove('show');document.getElementById('hub'+name[0].toUpperCase()+name.slice(1)).hidden=false}if(name==='food'){hideFoodOutsideHub(false);originals(true);drinks?.classList.remove('show');window.scrollTo({top:document.querySelector('.searchbox')?.offsetTop||0,behavior:'smooth'})}if(name==='drinks'){originals(false);hideFoodOutsideHub(true);document.getElementById('drinkTab')?.click();setTimeout(()=>{const d=document.getElementById('drinkCatalog');if(d){d.classList.add('show');d.scrollIntoView({behavior:'smooth',block:'start'})}},80)}}
  hub.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go));hub.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>typeof openR==='function'&&openR(+b.dataset.recipe));page('home')
}
boot()})();