// Stołownik — portal v10: twarde rozdzielenie widoków
(function(){
function boot(){
 if(typeof R==='undefined'||!document.querySelector('main'))return setTimeout(boot,120);
 document.getElementById('siteHub')?.remove();
 const main=document.querySelector('main');
 const foodNodes=[...main.children];
 foodNodes.forEach(x=>x.dataset.foodSection='1');
 const hub=document.createElement('div');hub.id='siteHub';
 const picks=R.filter(r=>r.img).slice(0,3);
 hub.innerHTML=`<nav class="hubNav" aria-label="Główna nawigacja"><button class="hubBrand" data-go="home"><span>Stołownik</span><small>kuchnia bez granic</small></button><div class="hubLinks"><button data-go="home">Start</button><button data-go="food">Przepisy</button><button data-go="drinks">Napoje</button><button data-go="gallery">Galeria</button><button data-go="story">O nas</button></div></nav>
 <section id="hubHome" class="hubPage"><section class="restaurantHero"><div class="heroCopy"><span class="eyebrow">JESIENNY STÓŁ · SMAKI ŚWIATA</span><h1>Smaki, do których chce się wracać.</h1><p>Przepisy z różnych stron świata podane po polsku — czytelnie, apetycznie i bez zbędnego chaosu.</p><div class="heroActions"><button data-go="food">Odkryj przepisy</button><button class="ghost" data-go="drinks">Zobacz napoje</button></div></div><div class="heroMosaic">${picks.map((r,i)=>`<button class="heroPhoto heroPhoto${i+1}" data-recipe="${r.id}"><img src="${r.img}" alt="${r.name}"><span><b>${r.name}</b><small>${r.time} min</small></span></button>`).join('')}</div></section><section class="quickSection"><div class="sectionIntro"><span class="eyebrow">STOŁOWNIK</span><h2>Wybierz sekcję</h2><p>Każda część serwisu ma teraz własną, oddzielną zawartość.</p></div><div class="hubTiles"><button data-go="food"><b>Przepisy</b><em>Dania i desery</em></button><button data-go="drinks"><b>Napoje</b><em>Napoje zimne i ciepłe</em></button><button data-go="gallery"><b>Galeria</b><em>Zdjęcia potraw</em></button><button data-go="story"><b>O nas</b><em>Poznaj Stołownik</em></button></div></section></section>
 <section id="hubGallery" class="hubPage" hidden><div class="sectionTitle galleryTitle"><span class="eyebrow">GALERIA</span><h2>Najpierw jedzą oczy</h2><p>Galeria zdjęć potraw ze Stołownika.</p></div><div class="galleryGrid">${R.filter(r=>r.img).slice(0,24).map(r=>`<button data-recipe="${r.id}"><img src="${r.img}" alt="${r.name}" loading="lazy"><span>${r.name}</span></button>`).join('')}</div></section>
 <section id="hubStory" class="hubPage" hidden><div class="storyHero"><span class="eyebrow">O STOŁOWNIKU</span><h2>Kuchnia bez granic, po polsku.</h2><p>Stołownik zbiera domowe klasyki i inspiracje z różnych stron świata. Stawiamy na czytelne przepisy, dobre zdjęcia i prostą nawigację.</p></div></section>`;
 main.prepend(hub);
 const st=document.createElement('style');st.id='siteHubStyle';st.textContent=`body>header,.top{display:none!important}main{max-width:none!important}.foodSectionHidden{display:none!important}#siteHub{max-width:1280px;margin:0 auto 45px;padding:18px 24px 0}.hubNav{position:sticky;top:10px;z-index:40;display:flex;justify-content:space-between;align-items:center;padding:12px 18px;background:#241a16f2;border-radius:18px}.hubBrand,.hubLinks button{border:0;background:transparent;color:#f7e8d4}.hubBrand span{display:block;font:700 30px Georgia,serif}.hubBrand small{color:#cda887}.hubLinks{display:flex;gap:6px;flex-wrap:wrap}.hubLinks button{padding:10px 14px;border-radius:999px;font-weight:700}.hubLinks button.active{background:#8d472f}.hubPage{margin-top:20px;overflow:hidden;background:#fffaf1;border:1px solid #d7b995;border-radius:22px}.restaurantHero{min-height:520px;display:grid;grid-template-columns:1fr 1fr;gap:35px;align-items:center;padding:55px;background:linear-gradient(125deg,#3a2921,#70452f);color:#fff4e6}.restaurantHero h1,.quickSection h2,.sectionTitle h2,.storyHero h2{font:700 56px/.95 Georgia,serif}.heroActions{display:flex;gap:10px;margin-top:25px}.heroActions button{padding:13px 18px;border:1px solid #a96849;border-radius:10px;background:#93472f;color:white;font-weight:800}.heroMosaic{display:grid;grid-template-columns:1fr 1fr;gap:10px}.heroPhoto{position:relative;height:210px;padding:0;border:0;border-radius:14px;overflow:hidden}.heroPhoto img{width:100%;height:100%;object-fit:cover}.heroPhoto span{position:absolute;left:0;right:0;bottom:0;padding:25px 10px 10px;background:linear-gradient(transparent,#211);color:white}.heroPhoto b,.heroPhoto small{display:block}.quickSection,.sectionTitle,.storyHero{padding:45px 34px}.hubTiles{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.hubTiles button{padding:24px;text-align:left;border:1px solid #dbc1a1;border-radius:14px;background:#fffaf1}.hubTiles b{display:block;font:700 28px Georgia,serif}.hubTiles em{font-style:normal}.galleryGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;padding:0 34px 45px}.galleryGrid button{padding:0;border:1px solid #dcc4a6;background:#f2e4d2;border-radius:13px;overflow:hidden}.galleryGrid img{width:100%;height:210px;object-fit:cover}.galleryGrid span{display:block;padding:12px}@media(max-width:760px){#siteHub{padding:10px 12px}.hubNav{position:static;flex-direction:column;align-items:flex-start;gap:10px}.restaurantHero{grid-template-columns:1fr;padding:32px 20px}.restaurantHero h1{font-size:44px}.hubTiles,.galleryGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(st);
 function currentFoodNodes(){return [...main.children].filter(x=>x!==hub&&x.id!=='drinkCatalog'&&x.dataset.foodSection==='1')}
 function hideFood(){currentFoodNodes().forEach(x=>x.classList.add('foodSectionHidden'));document.querySelectorAll('#countryFilter,#advancedFilters').forEach(x=>x.classList.add('foodSectionHidden'))}
 function showFood(){currentFoodNodes().forEach(x=>x.classList.remove('foodSectionHidden'));document.querySelectorAll('#countryFilter,#advancedFilters').forEach(x=>x.classList.remove('foodSectionHidden'))}
 function hideDrinks(){const d=document.getElementById('drinkCatalog');if(d){d.classList.remove('show');d.style.display='none'}}
 function showDrinks(){const d=document.getElementById('drinkCatalog');if(d){d.classList.remove('foodSectionHidden');d.style.display='block';d.classList.add('show')}}
 function page(name){
  document.querySelectorAll('#siteHub .hubPage').forEach(x=>x.hidden=true);
  document.querySelectorAll('.hubLinks button').forEach(x=>x.classList.toggle('active',x.dataset.go===name));
  hideFood();hideDrinks();
  if(name==='home')document.getElementById('hubHome').hidden=false;
  else if(name==='gallery')document.getElementById('hubGallery').hidden=false;
  else if(name==='story')document.getElementById('hubStory').hidden=false;
  else if(name==='food'){showFood();setTimeout(()=>document.querySelector('.searchbox,.section-head,.grid')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
  else if(name==='drinks'){document.getElementById('drinkTab')?.click();setTimeout(()=>{hideFood();showDrinks();document.getElementById('drinkCatalog')?.scrollIntoView({behavior:'smooth',block:'start'})},100)}
 }
 hub.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go));hub.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>typeof openR==='function'&&openR(+b.dataset.recipe));
 window.stolownikPage=page;page('home');
 setTimeout(()=>page('home'),250);
}
boot()})();