// Stołownik — pełny audyt estetyki i responsywności v8
(function(){
  if(!document.getElementById('stolownikEditorialFonts')){
    const l=document.createElement('link');l.id='stolownikEditorialFonts';l.rel='stylesheet';
    l.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;0,700;1,500;1,600;1,700&family=Manrope:wght@400;500;600;700;800&display=swap';
    document.head.appendChild(l);
  }
  const css=`
  :root{--cream:#f4e7d4;--paper:#fff9ef;--paper2:#f5e5d0;--ink:#2d211b;--muted:#735d4e;--rust:#91472f;--rust2:#ad5c38;--forest:#314a38;--copper:#c17a4b;--line:#d8bb98;--dark:#211713;--shadow:0 20px 55px #4a2d1d20}
  *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--dark)}body{margin:0!important;overflow-x:hidden!important;background:radial-gradient(circle at 12% 0,#fff9ee 0,transparent 26%),linear-gradient(180deg,#f5eadb 0%,#e6cfb4 100%)!important;color:var(--ink)!important;font-family:Manrope,system-ui,sans-serif!important;font-size:17px!important;line-height:1.55!important}
  img{max-width:100%}button,input,select,textarea{font:inherit}button{cursor:pointer;touch-action:manipulation}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #c77e4e55!important;outline-offset:2px!important}
  h1,h2,h3,.mainSiteName span,.hubBrand span,.card h3,.drinkBody h3,.inside h2,.featureGrid b,.hubTiles b,.storyCols b,.manifest blockquote{font-family:'Cormorant Garamond',Georgia,serif!important;font-style:italic!important}

  #siteHub{max-width:1320px!important;margin:0 auto 64px!important;padding:16px 20px 0!important}
  .hubNav{position:sticky!important;top:8px!important;z-index:80!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:20px!important;padding:12px 14px 12px 18px!important;background:#211713f2!important;border:1px solid #6a4835!important;border-radius:16px!important;box-shadow:0 16px 42px #24150d38!important;backdrop-filter:blur(16px)!important}
  .hubBrand{display:flex!important;flex-direction:column!important;align-items:flex-start!important;border:0!important;background:transparent!important;color:#fff1d9!important;padding:3px 8px!important}.hubBrand span{font-size:37px!important;font-weight:700!important;line-height:.85!important;letter-spacing:-.045em!important}.hubBrand small{margin-top:7px!important;font-size:9px!important;font-weight:800!important;letter-spacing:.18em!important;color:#d8ad87!important;text-transform:uppercase!important}
  .hubLinks{display:flex!important;align-items:center!important;gap:4px!important;flex-wrap:wrap!important}.hubLinks button{min-height:44px!important;border:1px solid transparent!important;background:transparent!important;color:#efddc9!important;border-radius:999px!important;padding:10px 15px!important;font-size:14px!important;font-weight:800!important}.hubLinks button:hover,.hubLinks button.active{background:#8b432d!important;border-color:#ad6849!important;color:#fff!important}
  .hubPage{overflow:hidden!important;background:var(--paper)!important;border:1px solid var(--line)!important;border-radius:18px!important;box-shadow:0 28px 76px #4e311f1d!important}

  #hubHome .restaurantHero{min-height:640px!important;display:grid!important;grid-template-columns:minmax(0,1.05fr) minmax(0,.95fr)!important;align-items:center!important;gap:48px!important;padding:58px clamp(30px,5vw,68px)!important;background:radial-gradient(circle at 12% 12%,#bd6a3b26,transparent 32%),radial-gradient(circle at 92% 84%,#712f1e2c,transparent 31%),linear-gradient(125deg,#291b16 0%,#4a2f24 52%,#70442f 100%)!important;color:#fff3e2!important;position:relative!important}
  #hubHome .restaurantHero:after{content:'';position:absolute;inset:0;background:repeating-linear-gradient(90deg,#ffffff05 0 1px,transparent 1px 96px);pointer-events:none}.heroCopy,.heroMosaic{position:relative!important;z-index:1!important;min-width:0!important}
  .mainSiteName{display:flex!important;flex-direction:column!important;align-items:flex-start!important;max-width:600px!important;margin:0 0 27px!important;padding-bottom:22px!important;border-bottom:1px solid #d29a7050!important}.mainSiteName span{font-size:clamp(76px,8vw,126px)!important;font-weight:700!important;line-height:.7!important;letter-spacing:-.065em!important;color:#fff1db!important}.mainSiteName small{margin-top:22px!important;font-size:11px!important;font-weight:800!important;letter-spacing:.24em!important;color:#d9a77d!important}
  .eyebrow{font-size:11px!important;font-weight:800!important;letter-spacing:.18em!important;text-transform:uppercase!important;color:#b65f39!important}.restaurantHero .eyebrow{color:#e1b183!important}
  #hubHome .restaurantHero h1{font-size:clamp(45px,4.7vw,68px)!important;font-weight:600!important;line-height:.94!important;letter-spacing:-.04em!important;margin:15px 0 18px!important;color:#fff0db!important;max-width:650px!important}
  #hubHome .restaurantHero p{font-size:18px!important;line-height:1.72!important;color:#ead6c2!important;max-width:650px!important;margin:0!important}
  .heroActions{display:flex!important;gap:10px!important;flex-wrap:wrap!important;margin-top:28px!important}.heroActions button{min-height:50px!important;border:1px solid #b96845!important;background:linear-gradient(135deg,#a95435,#843923)!important;color:#fff8ef!important;border-radius:10px!important;padding:14px 20px!important;font-size:15px!important;font-weight:800!important;box-shadow:0 12px 28px #1a0f0a38!important}.heroActions .ghost{background:transparent!important;border-color:#ba8969!important;color:#f2dac4!important;box-shadow:none!important}.heroActions button:hover{transform:translateY(-2px)!important}.heroNotes{display:flex!important;gap:9px!important;align-items:center!important;flex-wrap:wrap!important;margin-top:28px!important;color:#d1b59d!important;font-size:10px!important;font-weight:800!important;letter-spacing:.07em!important;text-transform:uppercase!important}
  .heroMosaic{display:grid!important;grid-template-columns:1fr 1fr!important;grid-template-rows:265px 215px!important;gap:13px!important}.heroPhoto{position:relative!important;overflow:hidden!important;border:1px solid #d2a37d4f!important;border-radius:13px!important;padding:0!important;background:#241711!important;box-shadow:0 24px 54px #160d0854!important}.heroPhoto1{grid-row:1/3!important}.heroPhoto img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important;transition:.35s!important}.heroPhoto:hover img{transform:scale(1.035)!important}.heroPhoto span{position:absolute!important;left:0!important;right:0!important;bottom:0!important;padding:50px 15px 15px!important;background:linear-gradient(transparent,#1b100bdd)!important;text-align:left!important;color:#fff!important}.heroPhoto b{display:block!important;font:italic 700 23px/1 'Cormorant Garamond',Georgia,serif!important}.heroPhoto small{font-size:12px!important;color:#e5cab3!important}

  .quickSection,.featured{padding:58px 32px!important}.quickSection{background:#f8ecdc!important}.sectionIntro,.sectionTitle{max-width:820px!important;margin-bottom:28px!important}.sectionIntro h2,.sectionTitle h2,.galleryTitle h2,.storyHero h2{font-size:clamp(43px,5vw,63px)!important;font-weight:600!important;line-height:.94!important;letter-spacing:-.03em!important;margin:9px 0 12px!important;color:#34251e!important}.sectionIntro p,.sectionTitle p,.storyHero p{font-size:16px!important;line-height:1.7!important;color:#735e4f!important}
  .hubTiles{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:13px!important}.hubTiles button{text-align:left!important;min-height:205px!important;padding:23px!important;border:1px solid #d8ba97!important;border-radius:13px!important;background:#fff9ef!important;box-shadow:0 8px 22px #51331f0e!important;display:flex!important;flex-direction:column!important}.hubTiles b{font-size:34px!important;font-weight:700!important;line-height:1!important;color:#33241d!important;margin:16px 0 9px!important}.hubTiles em{font-style:normal!important;color:#755f50!important;line-height:1.6!important;font-size:14px!important}.hubTiles strong{margin-top:auto!important;padding-top:20px!important;color:#7d3928!important;font-size:12px!important}.hubTiles button:hover{transform:translateY(-4px)!important;box-shadow:0 16px 32px #4f2f1d18!important}
  .featured{border-top:1px solid #ead2b6!important;background:#fff9ef!important}.featureGrid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:16px!important}.featureGrid button{border:1px solid #d9bc9a!important;background:#f3e4d0!important;padding:0!important;text-align:left!important;border-radius:13px!important;overflow:hidden!important}.featureGrid img{width:100%!important;height:240px!important;object-fit:cover!important;display:block!important}.featureGrid div{padding:17px!important}.featureGrid b{display:block!important;font-size:28px!important;line-height:1!important;color:#36251e!important}.featureGrid small{display:block!important;margin:7px 0 13px!important;color:#866957!important}.featureGrid button:hover{transform:translateY(-4px)!important;box-shadow:0 16px 32px #4e2f1d1b!important}
  .manifest{padding:66px 28px!important;text-align:center!important;background:linear-gradient(125deg,#2d4434,#3f5d44)!important;color:#f5e8d8!important}.manifest blockquote{font-size:clamp(41px,5vw,62px)!important;font-weight:600!important;line-height:.96!important;margin:11px 0 15px!important}.manifest p{font-size:16px!important;line-height:1.7!important;max-width:700px!important;margin:auto!important;color:#dccab8!important}

  #siteHub~.searchbox,#siteHub~.daybox,#siteHub~.section-head,#siteHub~.cats,#siteHub~.count,#siteHub~.grid,#siteHub~.foodfilters{max-width:1120px!important;margin-left:auto!important;margin-right:auto!important}
  .searchbox{padding:11px!important;border-radius:14px!important;background:#fff9f1f5!important;border:1px solid #d4b38e!important;box-shadow:var(--shadow)!important}.search{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;gap:10px!important}.search input,#drinkQ{min-height:56px!important;border:1px solid #d6ba99!important;border-radius:10px!important;background:#fffdf8!important;font-size:16px!important;padding:14px 17px!important;color:#34261f!important}
  .surprise,.open,.daybtn,.resetfilters,.drinkOpen{min-height:48px!important;border:1px solid #70301f!important;background:linear-gradient(180deg,#93472f,#783522)!important;color:#fff8ef!important;border-radius:9px!important;padding:12px 17px!important;font-size:15px!important;font-weight:800!important;box-shadow:0 8px 18px #5d2b1b20!important}.surprise:hover,.open:hover,.daybtn:hover,.resetfilters:hover,.drinkOpen:hover{transform:translateY(-1px)!important}
  .daybox{margin-bottom:48px!important;padding:28px 30px!important;border-radius:14px!important;background:linear-gradient(130deg,#293f30,#405d45)!important;border:1px solid #617765!important;box-shadow:0 18px 40px #24352922!important}.daybox h2{font:italic 600 39px/1 'Cormorant Garamond',Georgia,serif!important;color:#fff0dd!important}.daybox p{font-size:15px!important;line-height:1.65!important;color:#ddd6c9!important}.daycontrols select{min-height:46px!important;border:1px solid #c7b39a!important;border-radius:9px!important;background:#fffaf0!important;padding:9px 12px!important}
  .section-head{margin-top:52px!important;margin-bottom:20px!important;display:grid!important;grid-template-columns:minmax(0,1fr) minmax(260px,460px)!important;align-items:end!important;gap:30px!important}.section-head h2{font:italic 600 clamp(43px,5vw,59px)/.96 'Cormorant Garamond',Georgia,serif!important;color:#34251e!important;margin:0!important}.section-head p{font-size:15px!important;line-height:1.7!important;color:#766153!important}.cats,.drinkPills{display:flex!important;gap:8px!important;flex-wrap:wrap!important}.cat,.drinkPill{min-height:42px!important;border:1px solid #d5b793!important;background:#fff8ed!important;border-radius:999px!important;padding:9px 14px!important;font-size:13px!important;font-weight:800!important;color:#584337!important}.cat.active,.drinkPill.on{background:#7e3927!important;border-color:#7e3927!important;color:#fff!important}.foodfilters{background:#edddc7!important;border:1px solid #d4b691!important;border-radius:14px!important;padding:18px!important}.filterbox{background:#fff9ef!important;border:1px solid #d9c0a0!important;border-radius:9px!important}.range input{min-height:44px!important;border:1px solid #d7b99a!important;border-radius:8px!important;background:#fffdf9!important;padding:9px!important}
  .grid,.drinkGrid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:20px!important}.card,.drinkCard{min-width:0!important;background:#fff9ef!important;border:1px solid #d8bc9a!important;border-radius:14px!important;overflow:hidden!important;box-shadow:0 9px 25px #50331f12!important}.card:hover,.drinkCard:hover{transform:translateY(-4px)!important;box-shadow:0 19px 38px #50331f20!important}.card img,.drinkCard img{width:100%!important;height:250px!important;object-fit:cover!important;display:block!important}.pad,.drinkBody{padding:18px!important}.card h3,.drinkBody h3{font-size:31px!important;font-weight:700!important;line-height:1!important;color:#34241d!important;margin:11px 0 8px!important}.card p{font-size:14px!important;line-height:1.65!important;color:#755f51!important}.open,.drinkOpen{width:100%!important;margin-top:13px!important}
  .drinkCat{max-width:1240px!important;margin:16px auto 64px!important;padding:42px 34px 54px!important;background:#fff9ef!important;border:1px solid #d5b38d!important;border-radius:18px!important}.drinkCat .section-head{margin-top:0!important}.drinkRecipe{z-index:10020!important}
  .galleryTitle{padding:50px 32px 9px!important}.galleryGrid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:13px!important;padding:12px 32px 44px!important}.galleryGrid button{min-width:0!important;border:1px solid #d8bd9d!important;background:#f3e3cf!important;border-radius:12px!important;overflow:hidden!important;padding:0!important;text-align:left!important}.galleryGrid img{width:100%!important;height:210px!important;object-fit:cover!important}.galleryGrid span{display:block!important;padding:13px!important;font-size:14px!important;font-weight:800!important;color:#49352a!important}
  .storyHero{padding:68px clamp(30px,7vw,84px)!important;background:linear-gradient(120deg,#31231c,#4b3024)!important;color:#f5e9d9!important}.storyHero h2{color:#fff0dc!important}.storyHero p{color:#dcc9b7!important;max-width:820px!important}.storyCols{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:1px!important;background:#d4b99a!important}.storyCols article{padding:32px!important;background:#fff9ef!important}.storyCols b{display:block!important;font-size:30px!important;color:#3d2b22!important;margin:11px 0 7px!important}.storyCols p{font-size:14px!important;line-height:1.68!important;color:#725d4d!important}

  .modal{z-index:9999!important}.sheet{background:#fff9ef!important;border:1px solid #d3b58f!important;border-radius:16px!important;box-shadow:0 40px 100px #170e0966!important;overflow:auto!important;max-height:92vh!important}.sheet>img{width:100%!important;height:390px!important;object-fit:cover!important}.inside{padding:30px!important}.inside h2{font-size:clamp(41px,5vw,56px)!important;font-weight:600!important;line-height:.96!important;color:#33231c!important}.inside h3{font-size:28px!important;color:#3a2a22!important}.recipebar{background:#efdec8!important;border:1px solid #dcc09d!important;border-radius:10px!important}.nut{background:#e3eadf!important;border:1px solid #c7d2c2!important;border-radius:9px!important}.recipeactions button{min-height:44px!important}
  footer{background:#201611!important;border-top:4px solid #823d29!important;color:#dfc5ab!important;padding:42px 20px!important;text-align:center!important}

  @media(max-width:1020px){
    #hubHome .restaurantHero{grid-template-columns:1fr!important;gap:34px!important;min-height:auto!important}.heroMosaic{max-width:820px!important;width:100%!important}.hubTiles{grid-template-columns:repeat(2,minmax(0,1fr))!important}.featureGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.galleryGrid{grid-template-columns:repeat(3,minmax(0,1fr))!important}.grid,.drinkGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.section-head{grid-template-columns:1fr!important}.storyCols{grid-template-columns:1fr!important}
  }
  @media(max-width:760px){
    body{font-size:16px!important;padding-bottom:env(safe-area-inset-bottom)!important}#siteHub{padding:8px 8px 0!important;margin-bottom:40px!important}.hubNav{top:5px!important;align-items:flex-start!important;flex-direction:column!important;gap:9px!important;padding:11px!important;border-radius:13px!important}.hubBrand span{font-size:34px!important}.hubLinks{width:100%!important;overflow-x:auto!important;flex-wrap:nowrap!important;padding:1px 0 3px!important;scrollbar-width:none!important}.hubLinks::-webkit-scrollbar{display:none!important}.hubLinks button{flex:0 0 auto!important;min-height:42px!important;padding:9px 13px!important;font-size:13px!important}
    #hubHome .restaurantHero{padding:40px 19px!important;gap:28px!important}.mainSiteName{margin-bottom:22px!important;padding-bottom:18px!important}.mainSiteName span{font-size:clamp(66px,19vw,92px)!important}.mainSiteName small{font-size:9px!important;letter-spacing:.19em!important;margin-top:18px!important}.restaurantHero .eyebrow{font-size:10px!important}.restaurantHero h1{font-size:42px!important}.restaurantHero p{font-size:16px!important;line-height:1.65!important}.heroActions{flex-direction:column!important}.heroActions button{width:100%!important;min-height:52px!important}.heroNotes{font-size:9px!important}.heroMosaic{grid-template-columns:1fr 1fr!important;grid-template-rows:215px 165px!important}.heroPhoto b{font-size:20px!important}
    .quickSection,.featured{padding:42px 16px!important}.sectionIntro h2,.sectionTitle h2,.galleryTitle h2,.storyHero h2{font-size:42px!important}.hubTiles{grid-template-columns:1fr!important}.hubTiles button{min-height:160px!important}.featureGrid{grid-template-columns:1fr!important}.featureGrid img{height:225px!important}.galleryGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important;padding-left:16px!important;padding-right:16px!important}.galleryGrid img{height:180px!important}
    #siteHub~.searchbox,#siteHub~.daybox,#siteHub~.section-head,#siteHub~.cats,#siteHub~.count,#siteHub~.grid,#siteHub~.foodfilters{margin-left:10px!important;margin-right:10px!important}.search{grid-template-columns:1fr!important}.surprise{width:100%!important}.daybox{padding:23px 18px!important}.daycontrols{display:grid!important;grid-template-columns:1fr!important;gap:8px!important}.daycontrols select,.daybtn{width:100%!important}.grid,.drinkGrid{grid-template-columns:1fr!important}.card,.drinkCard{border-radius:16px!important}.card img,.drinkCard img{height:235px!important}.card .pad,.drinkBody{padding:17px!important}.card h3,.drinkBody h3{font-size:30px!important}.card p{font-size:15px!important}.open,.drinkOpen{min-height:52px!important;font-size:16px!important}.drinkCat{margin:10px!important;padding:28px 14px 38px!important}.foodfilters{padding:14px!important}
    .modal{padding:0!important;align-items:stretch!important;justify-content:stretch!important;background:#1b110ddd!important;overscroll-behavior:contain!important}.modal.show{display:flex!important}.sheet{width:100%!important;max-width:none!important;height:100dvh!important;max-height:100dvh!important;margin:0!important;border:0!important;border-radius:0!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important}.sheet>img{height:220px!important;min-height:220px!important}.close{position:fixed!important;right:12px!important;top:calc(10px + env(safe-area-inset-top))!important;width:48px!important;height:48px!important;z-index:10002!important;border:1px solid #d8b994!important;background:#fff9eff2!important;color:#35231b!important;font-size:28px!important;box-shadow:0 8px 24px #1d100b42!important}.inside{padding:22px 16px calc(40px + env(safe-area-inset-bottom))!important}.inside h2{font-size:clamp(38px,11vw,48px)!important;margin:10px 0 12px!important}.recipebar{display:grid!important;grid-template-columns:1fr!important;gap:9px!important;padding:14px!important}.recipebar input,.recipebar select{width:100%!important;min-height:48px!important;font-size:16px!important}.nutrition{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.cols{grid-template-columns:1fr!important}.inside h3{font-size:30px!important}.step{display:grid!important;grid-template-columns:56px minmax(0,1fr)!important;gap:10px!important}.steptext{font-size:16px!important;line-height:1.6!important;overflow-wrap:anywhere!important}
    .drinkRecipe{padding:0!important;align-items:stretch!important}.drinkSheet{width:100%!important;height:100dvh!important;max-height:100dvh!important;border-radius:0!important;-webkit-overflow-scrolling:touch!important}.drinkSheet img{height:220px!important}.drinkInside{padding:22px 16px calc(40px + env(safe-area-inset-bottom))!important}.drinkInside h2{font-size:40px!important}.drinkClose{position:fixed!important;top:calc(10px + env(safe-area-inset-top))!important;right:12px!important;width:48px!important;height:48px!important}
    .storyHero{padding:50px 20px!important}.storyCols article{padding:26px 20px!important}
  }
  @media(max-width:480px){.mainSiteName span{font-size:68px!important}.restaurantHero h1{font-size:38px!important}.heroMosaic{grid-template-columns:1fr!important;grid-template-rows:225px 175px 175px!important}.heroPhoto1{grid-row:auto!important}.galleryGrid{grid-template-columns:1fr!important}.galleryGrid img{height:220px!important}.section-head h2{font-size:40px!important}.manifest blockquote{font-size:40px!important}.nutrition{grid-template-columns:1fr 1fr!important}}
  @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
  `;
  let s=document.getElementById('stolownikProStyle')||document.createElement('style');s.id='stolownikProStyle';s.textContent=css;if(!s.parentNode)document.head.appendChild(s);

  function lockRecipe(){const m=document.getElementById('modal');if(m&&m.classList.contains('show')){document.body.style.overflow='hidden';const sh=m.querySelector('.sheet');if(sh&&innerWidth<=760)sh.scrollTop=0}}
  document.addEventListener('click',e=>{if(e.target.closest&&e.target.closest('.card .open'))setTimeout(lockRecipe,0)},true);
  const observer=new MutationObserver(()=>{const m=document.getElementById('modal');if(!m)return;if(!m.classList.contains('show')&&document.body.style.overflow==='hidden'&&!document.querySelector('.drinkRecipe.show'))document.body.style.overflow=''});
  const watch=()=>{const m=document.getElementById('modal');if(m)observer.observe(m,{attributes:true,attributeFilter:['class']});else setTimeout(watch,150)};watch();
})();