// Stołownik — jesienny restauracyjny redesign v6
(function(){
  if(!document.getElementById('stolownikEditorialFonts')){
    const l=document.createElement('link');l.id='stolownikEditorialFonts';l.rel='stylesheet';
    l.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;0,700;1,500;1,600;1,700&family=Manrope:wght@400;500;600;700;800&display=swap';
    document.head.appendChild(l);
  }
  const css=`
  :root{--cream:#f2e4cf;--paper:#fff9ef;--paper2:#f7ead7;--ink:#2d211b;--muted:#745f50;--wine:#7d3928;--rust:#a95833;--copper:#c47b4d;--forest:#314b39;--line:#d6b591;--dark:#211713}
  *{box-sizing:border-box}html{scroll-behavior:smooth;background:#211713}body{margin:0!important;background:radial-gradient(circle at 12% 0,#fff8ec 0,transparent 24%),linear-gradient(180deg,#f4e7d5 0%,#e5cdb1 100%)!important;color:var(--ink)!important;font-family:Manrope,system-ui,sans-serif!important;font-size:17px!important}
  body>.top{background:#1f1511!important;color:#e4c7a9!important;padding:11px 16px!important;text-align:center!important;font-size:12px!important;font-weight:800!important;letter-spacing:.2em!important;text-transform:uppercase!important}
  h1,h2,h3,.mainSiteName span,.hubBrand span,.card h3,.drinkBody h3,.inside h2,.featureGrid b,.hubTiles b,.storyCols b,.manifest blockquote{font-family:'Cormorant Garamond',Georgia,serif!important}
  button,input,select{font-family:Manrope,system-ui,sans-serif!important}button{cursor:pointer}

  #siteHub{max-width:1320px!important;margin:0 auto 70px!important;padding:18px 22px 0!important}
  .hubNav{position:sticky!important;top:10px!important;z-index:50!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:24px!important;padding:12px 16px 12px 20px!important;background:#201611f2!important;border:1px solid #6b4937!important;border-radius:16px!important;box-shadow:0 18px 48px #28180f38!important;backdrop-filter:blur(18px)!important}
  .hubBrand{display:flex!important;flex-direction:column!important;align-items:flex-start!important;border:0!important;background:transparent!important;color:#fff1d9!important;padding:2px 6px!important}.hubBrand span{font-size:36px!important;font-style:italic!important;font-weight:700!important;line-height:.88!important;letter-spacing:-.045em!important}.hubBrand small{font-size:9px!important;line-height:1!important;margin-top:7px!important;color:#d6aa83!important;letter-spacing:.18em!important;font-weight:800!important;text-transform:uppercase!important}
  .hubLinks{display:flex!important;align-items:center!important;gap:4px!important;flex-wrap:wrap!important}.hubLinks button{border:1px solid transparent!important;background:transparent!important;color:#edd8c2!important;border-radius:999px!important;padding:11px 16px!important;font-size:14px!important;font-weight:800!important;transition:.2s!important}.hubLinks button:hover,.hubLinks button.active{background:#8d442d!important;border-color:#a96545!important;color:#fff!important;transform:translateY(-1px)!important}
  .hubPage{overflow:hidden!important;background:#fff9ef!important;border:1px solid #d5b38d!important;border-radius:18px!important;box-shadow:0 30px 80px #52331f1c!important}

  #hubHome .restaurantHero{min-height:650px!important;display:grid!important;grid-template-columns:1.05fr .95fr!important;align-items:center!important;gap:54px!important;padding:64px clamp(34px,5vw,72px)!important;background:radial-gradient(circle at 12% 10%,#b96a3c2a,transparent 31%),radial-gradient(circle at 90% 80%,#6d2f1d2f,transparent 32%),linear-gradient(125deg,#2a1c17 0%,#4a2f24 53%,#71442f 100%)!important;color:#fff4e4!important;position:relative!important}
  #hubHome .restaurantHero:after{content:''!important;position:absolute!important;inset:0!important;background:repeating-linear-gradient(90deg,#ffffff05 0 1px,transparent 1px 92px)!important;pointer-events:none!important}
  #hubHome .heroCopy,#hubHome .heroMosaic{position:relative!important;z-index:2!important}
  .mainSiteName{display:flex!important;flex-direction:column!important;align-items:flex-start!important;max-width:560px!important;margin:0 0 30px!important;padding-bottom:24px!important;border-bottom:1px solid #d29b7050!important}.mainSiteName span{font-size:clamp(78px,8.3vw,128px)!important;font-style:italic!important;font-weight:700!important;line-height:.7!important;letter-spacing:-.065em!important;color:#fff2dc!important;text-shadow:0 14px 36px #130b074f!important}.mainSiteName small{margin-top:24px!important;font-size:11px!important;font-weight:800!important;letter-spacing:.26em!important;color:#d8a77d!important}
  .eyebrow{font-size:12px!important;font-weight:800!important;letter-spacing:.2em!important;text-transform:uppercase!important;color:#bc7049!important}.restaurantHero .eyebrow{color:#e0b084!important}
  #hubHome .restaurantHero h1{font-size:clamp(47px,5vw,70px)!important;font-style:italic!important;font-weight:600!important;line-height:.92!important;letter-spacing:-.045em!important;margin:17px 0 20px!important;color:#fff1dc!important;max-width:650px!important}
  #hubHome .restaurantHero p{font-size:19px!important;line-height:1.75!important;color:#ead7c4!important;max-width:640px!important;margin:0!important}
  .heroActions{display:flex!important;gap:11px!important;flex-wrap:wrap!important;margin-top:32px!important}.heroActions button{border:1px solid #b86743!important;background:linear-gradient(135deg,#aa5836,#873c28)!important;color:#fff7ed!important;border-radius:10px!important;padding:16px 22px!important;font-size:15px!important;font-weight:800!important;box-shadow:0 12px 28px #1c100a38!important;transition:.2s!important}.heroActions button:hover{transform:translateY(-2px)!important;box-shadow:0 17px 34px #170d093d!important}.heroActions .ghost{background:transparent!important;border-color:#bd8c6d!important;color:#f2dac4!important;box-shadow:none!important}.heroActions .ghost:hover{background:#fff8ec0d!important}
  .heroNotes{display:flex!important;gap:10px!important;align-items:center!important;flex-wrap:wrap!important;margin-top:32px!important;color:#d3b79e!important;font-size:11px!important;font-weight:800!important;letter-spacing:.07em!important;text-transform:uppercase!important}.heroNotes i{width:4px!important;height:4px!important;border-radius:50%!important;background:#b5623d!important}
  .heroMosaic{display:grid!important;grid-template-columns:1fr 1fr!important;grid-template-rows:270px 220px!important;gap:14px!important}.heroPhoto{position:relative!important;overflow:hidden!important;border:1px solid #d6aa8454!important;border-radius:13px!important;padding:0!important;background:#241812!important;box-shadow:0 26px 58px #160d0857!important}.heroPhoto1{grid-row:1/3!important}.heroPhoto img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important;filter:saturate(.9) contrast(1.04)!important;transition:.45s!important}.heroPhoto:hover img{transform:scale(1.04)!important}.heroPhoto span{position:absolute!important;left:0!important;right:0!important;bottom:0!important;padding:52px 16px 16px!important;background:linear-gradient(transparent,#1b100bdd)!important;text-align:left!important;color:#fff!important}.heroPhoto b{display:block!important;font:italic 700 24px/1 'Cormorant Garamond',Georgia,serif!important}.heroPhoto small{display:block!important;margin-top:5px!important;font-size:12px!important;color:#e5cbb5!important}

  .quickSection,.featured{padding:64px 34px 62px!important}.quickSection{background:#f8ecdc!important}.sectionIntro,.sectionTitle{max-width:800px!important;margin-bottom:30px!important}.sectionIntro h2,.sectionTitle h2,.galleryTitle h2,.storyHero h2{font-size:clamp(44px,5.1vw,64px)!important;font-style:italic!important;font-weight:600!important;line-height:.93!important;letter-spacing:-.035em!important;margin:10px 0 13px!important;color:#34251e!important}.sectionIntro p,.sectionTitle p,.storyHero p{font-size:17px!important;line-height:1.72!important;color:#735f50!important}
  .hubTiles{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:14px!important}.hubTiles button{text-align:left!important;min-height:225px!important;padding:25px!important;border:1px solid #d7b994!important;border-radius:13px!important;background:#fff9ef!important;box-shadow:0 9px 25px #51331f0f!important;display:flex!important;flex-direction:column!important;transition:.22s!important}.hubTiles button:hover{transform:translateY(-5px)!important;border-color:#bc845f!important;box-shadow:0 18px 34px #4f2f1d1a!important}.hubTiles span{font-size:12px!important;font-weight:800!important;color:#a35031!important;letter-spacing:.14em!important}.hubTiles b{font-size:35px!important;font-style:italic!important;font-weight:700!important;line-height:1!important;color:#33241d!important;margin:18px 0 10px!important}.hubTiles em{font-style:normal!important;color:#755f50!important;line-height:1.65!important;font-size:14px!important}.hubTiles strong{margin-top:auto!important;padding-top:24px!important;color:#7d3928!important;font-size:12px!important;letter-spacing:.05em!important;text-transform:uppercase!important}
  .featured{border-top:1px solid #ead3b7!important;background:#fff9ef!important}.featureGrid{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:17px!important}.featureGrid button{border:1px solid #d9bd9d!important;background:#f4e5d2!important;padding:0!important;text-align:left!important;border-radius:13px!important;overflow:hidden!important;transition:.22s!important}.featureGrid button:hover{transform:translateY(-5px)!important;box-shadow:0 18px 36px #4d301e20!important}.featureGrid img{width:100%!important;height:245px!important;object-fit:cover!important;display:block!important}.featureGrid div{padding:18px!important}.featureGrid b{display:block!important;font-size:28px!important;font-style:italic!important;line-height:1!important;color:#36251e!important}.featureGrid small{display:block!important;margin:7px 0 14px!important;color:#866957!important;font-size:13px!important}.featureGrid strong{font-size:11px!important;letter-spacing:.09em!important;text-transform:uppercase!important;color:#8b422a!important}
  .manifest{padding:74px 30px!important;text-align:center!important;background:radial-gradient(circle at 18% 0,#d4ad7b18,transparent 34%),linear-gradient(125deg,#2d4434,#3d5b42)!important;color:#f5e8d8!important}.manifest .eyebrow{color:#dab18b!important}.manifest blockquote{font-size:clamp(42px,5vw,64px)!important;font-style:italic!important;font-weight:600!important;line-height:.96!important;margin:12px 0 16px!important}.manifest p{font-size:17px!important;line-height:1.7!important;max-width:700px!important;margin:auto!important;color:#dccab8!important}

  #siteHub~.searchbox,#siteHub~.daybox,#siteHub~.section-head,#siteHub~.cats,#siteHub~.count,#siteHub~.grid,#siteHub~.foodfilters{max-width:1120px!important;margin-left:auto!important;margin-right:auto!important}
  #siteHub~.searchbox{margin-top:30px!important}.searchbox{padding:11px!important;border-radius:14px!important;background:#fff9f1f4!important;border:1px solid #d4b38e!important;box-shadow:0 18px 48px #42291a1e!important}.search{display:grid!important;grid-template-columns:1fr auto!important;gap:10px!important}.search input,#drinkQ{min-height:58px!important;border:1px solid #d6ba99!important;border-radius:10px!important;background:#fffdf8!important;font-size:17px!important;padding:15px 18px!important;color:#34261f!important;outline:none!important}.search input:focus,#drinkQ:focus{border-color:#a95b39!important;box-shadow:0 0 0 3px #a95b3918!important}
  .surprise,.open,.daybtn,.resetfilters{border:1px solid #70301f!important;background:linear-gradient(180deg,#93472f,#783522)!important;color:#fff8ef!important;border-radius:9px!important;padding:13px 18px!important;font-size:15px!important;font-weight:800!important;box-shadow:0 8px 18px #5d2b1b23!important;transition:.18s!important}.surprise:hover,.open:hover,.daybtn:hover,.resetfilters:hover{transform:translateY(-2px)!important;background:linear-gradient(180deg,#a65435,#7c3623)!important}
  .daybox{position:relative!important;overflow:hidden!important;margin-top:0!important;margin-bottom:55px!important;padding:32px 34px!important;border-radius:14px!important;background:radial-gradient(circle at 90% 0,#d7b77b18,transparent 31%),linear-gradient(130deg,#283d2f,#3f5d45)!important;border:1px solid #607664!important;box-shadow:0 18px 40px #24352922!important}.daybox h2{font:italic 600 40px/1 'Cormorant Garamond',Georgia,serif!important;color:#fff0dd!important;margin:0 0 8px!important}.daybox p{font-size:16px!important;line-height:1.65!important;color:#d9d4c6!important}.daycontrols select{min-height:48px!important;border:1px solid #c7b39a!important;border-radius:9px!important;background:#fffaf0!important;padding:10px 12px!important}
  .section-head{margin-top:58px!important;margin-bottom:22px!important;display:grid!important;grid-template-columns:1fr minmax(280px,480px)!important;align-items:end!important;gap:34px!important}.section-head h2{font:italic 600 clamp(44px,5vw,60px)/.96 'Cormorant Garamond',Georgia,serif!important;color:#34251e!important;margin:0!important}.section-head p{font-size:16px!important;line-height:1.7!important;color:#766153!important}.cats{display:flex!important;gap:8px!important;flex-wrap:wrap!important;margin-bottom:20px!important}.cat,.drinkPill{border:1px solid #d5b793!important;background:#fff8ed!important;border-radius:999px!important;padding:11px 16px!important;font-size:14px!important;font-weight:800!important;color:#584337!important;transition:.18s!important}.cat:hover,.drinkPill:hover{transform:translateY(-1px)!important;background:#f0dec7!important}.cat.active,.drinkPill.on{background:#7e3927!important;border-color:#7e3927!important;color:#fff!important}.count{font-size:14px!important;color:#6d5749!important;font-weight:800!important}
  .foodfilters{background:#edddc7!important;border:1px solid #d4b691!important;border-radius:14px!important;padding:20px!important;box-shadow:inset 0 1px #fff8!important}.filtertop h3{font:italic 600 28px/1 'Cormorant Garamond',Georgia,serif!important}.filterbox{background:#fff9ef!important;border:1px solid #d9c0a0!important;border-radius:9px!important}.range input{border:1px solid #d7b99a!important;border-radius:8px!important;background:#fffdf9!important;padding:10px!important}
  .grid,.drinkGrid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:22px!important}.card,.drinkCard{background:#fff9ef!important;border:1px solid #d8bc9a!important;border-radius:14px!important;overflow:hidden!important;box-shadow:0 10px 28px #50331f12!important;transition:.23s!important}.card:hover,.drinkCard:hover{transform:translateY(-6px)!important;border-color:#bd8964!important;box-shadow:0 22px 44px #50331f24!important}.card img,.drinkCard img{width:100%!important;height:260px!important;object-fit:cover!important;display:block!important;filter:saturate(.92) contrast(1.035)!important}.pad,.drinkBody{padding:20px!important}.tag{background:#ecd9c1!important;color:#604638!important;border-radius:999px!important;padding:5px 9px!important;font-size:12px!important;font-weight:800!important}.timebadge{background:#fff9efeb!important;color:#473128!important;border:1px solid #ead4b7!important;border-radius:999px!important;padding:7px 10px!important;font-size:13px!important}.card h3,.drinkBody h3{font-size:32px!important;font-style:italic!important;font-weight:700!important;line-height:1!important;color:#34241d!important;margin:12px 0 9px!important}.card p{font-size:15px!important;line-height:1.68!important;color:#755f51!important}.open{margin-top:auto!important}
  .drinkCat{max-width:1240px!important;margin:18px auto 70px!important;padding:46px 38px 60px!important;background:#fff9ef!important;border:1px solid #d5b38d!important;border-radius:18px!important}.drinkCat .section-head h2{font-style:italic!important}.drinkPills{margin:22px 0 28px!important}
  .galleryTitle{padding:54px 34px 10px!important}.galleryGrid{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:14px!important;padding:12px 34px 48px!important}.galleryGrid button{border:1px solid #d8bd9d!important;background:#f3e3cf!important;border-radius:12px!important;overflow:hidden!important;padding:0!important;text-align:left!important}.galleryGrid img{width:100%!important;height:220px!important;object-fit:cover!important}.galleryGrid span{display:block!important;padding:14px!important;font-size:15px!important;font-weight:800!important;color:#49352a!important}
  .storyHero{padding:78px clamp(34px,7vw,90px)!important;background:radial-gradient(circle at 85% 10%,#b77a4c2d,transparent 30%),linear-gradient(120deg,#31231c,#4b3024)!important;color:#f5e9d9!important}.storyHero h2{color:#fff0dc!important}.storyHero p{color:#dcc9b7!important;max-width:820px!important}.storyCols{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:1px!important;background:#d4b99a!important}.storyCols article{padding:36px!important;background:#fff9ef!important}.storyCols b{display:block!important;font-size:31px!important;font-style:italic!important;color:#3d2b22!important;margin:12px 0 8px!important}.storyCols p{font-size:15px!important;line-height:1.68!important;color:#725d4d!important}
  .sheet{background:#fff9ef!important;border:1px solid #d3b58f!important;border-radius:16px!important;box-shadow:0 40px 100px #170e0966!important;overflow:hidden!important}.sheet>img{height:420px!important;object-fit:cover!important}.inside{padding:34px!important}.inside h2{font-size:clamp(42px,5vw,58px)!important;font-style:italic!important;font-weight:600!important;line-height:.95!important;color:#33231c!important}.inside h3{font-size:29px!important;font-style:italic!important;color:#3a2a22!important}.recipebar{background:#efdec8!important;border:1px solid #dcc09d!important;border-radius:10px!important}.nut{background:#e3eadf!important;border:1px solid #c7d2c2!important;border-radius:9px!important}.stepmin{background:#314b39!important}.close{border-radius:50%!important}footer{background:#201611!important;border-top:4px solid #823d29!important;color:#dfc5ab!important;padding:46px 20px!important;text-align:center!important}

  @media(max-width:1020px){
    #hubHome .restaurantHero{grid-template-columns:1fr!important;gap:38px!important;min-height:auto!important}.heroMosaic{max-width:820px!important;width:100%!important}.hubTiles{grid-template-columns:repeat(2,1fr)!important}.featureGrid{grid-template-columns:repeat(2,1fr)!important}.galleryGrid{grid-template-columns:repeat(3,1fr)!important}.grid,.drinkGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.section-head{grid-template-columns:1fr!important}.storyCols{grid-template-columns:1fr!important}
  }
  @media(max-width:760px){
    body{font-size:16px!important}#siteHub{padding:10px 10px 0!important;margin-bottom:46px!important}.hubNav{position:sticky!important;top:6px!important;align-items:flex-start!important;flex-direction:column!important;gap:10px!important;padding:12px!important;border-radius:13px!important}.hubBrand span{font-size:34px!important}.hubLinks{width:100%!important;overflow-x:auto!important;flex-wrap:nowrap!important;padding-bottom:2px!important;scrollbar-width:none!important}.hubLinks::-webkit-scrollbar{display:none!important}.hubLinks button{flex:0 0 auto!important;padding:10px 13px!important;font-size:13px!important}
    #hubHome .restaurantHero{padding:44px 22px!important;gap:31px!important}.mainSiteName{margin-bottom:26px!important;padding-bottom:20px!important}.mainSiteName span{font-size:clamp(68px,19vw,96px)!important}.mainSiteName small{font-size:9px!important;letter-spacing:.2em!important;margin-top:20px!important}.restaurantHero .eyebrow{font-size:10px!important}.restaurantHero h1{font-size:44px!important}.restaurantHero p{font-size:17px!important;line-height:1.65!important}.heroActions{flex-direction:column!important}.heroActions button{width:100%!important}.heroNotes{font-size:10px!important}.heroMosaic{grid-template-columns:1fr 1fr!important;grid-template-rows:225px 175px!important}.heroPhoto b{font-size:20px!important}
    .quickSection,.featured{padding:46px 18px!important}.sectionIntro h2,.sectionTitle h2,.galleryTitle h2,.storyHero h2{font-size:44px!important}.hubTiles{grid-template-columns:1fr!important}.hubTiles button{min-height:175px!important}.featureGrid{grid-template-columns:1fr!important}.featureGrid img{height:235px!important}.galleryGrid{grid-template-columns:repeat(2,1fr)!important;padding-left:18px!important;padding-right:18px!important}.galleryGrid img{height:190px!important}
    #siteHub~.searchbox,#siteHub~.daybox,#siteHub~.section-head,#siteHub~.cats,#siteHub~.count,#siteHub~.grid,#siteHub~.foodfilters{margin-left:12px!important;margin-right:12px!important}.search{grid-template-columns:1fr!important}.surprise{width:100%!important}.daybox{grid-template-columns:1fr!important;padding:25px 20px!important}.daycontrols{display:grid!important;grid-template-columns:1fr!important}.daycontrols select,.daybtn{width:100%!important}.grid,.drinkGrid{grid-template-columns:1fr!important}.card img,.drinkCard img{height:250px!important}.drinkCat{margin:12px!important;padding:30px 16px 42px!important}.foodfilters{padding:15px!important}.sheet>img{height:275px!important}.inside{padding:22px!important}.inside h2{font-size:40px!important}.nutrition{grid-template-columns:repeat(2,1fr)!important}.cols{grid-template-columns:1fr!important}.storyHero{padding:55px 22px!important}.storyCols article{padding:28px 22px!important}
  }
  @media(max-width:480px){
    .mainSiteName span{font-size:70px!important}.restaurantHero h1{font-size:40px!important}.heroMosaic{grid-template-columns:1fr!important;grid-template-rows:235px 185px 185px!important}.heroPhoto1{grid-row:auto!important}.galleryGrid{grid-template-columns:1fr!important}.galleryGrid img{height:230px!important}.card h3,.drinkBody h3{font-size:30px!important}.section-head h2{font-size:42px!important}.manifest blockquote{font-size:42px!important}
  }
  @media (prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
  `;
  let s=document.getElementById('stolownikProStyle')||document.createElement('style');s.id='stolownikProStyle';s.textContent=css;if(!s.parentNode)document.head.appendChild(s);
})();